### ISSUE TITLE
query for tags doesn't read through alias

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#100]
I thought it would be clever to improve ergonomics like this:

`BUILD`
```
alias(name = "devserver", actual = "//src:devserver")
```

`src/BUILD`
```
my_rule(name = "devserver", tags=["ibazel_live_reload", "ibazel_notify_changes"])
```

but if I now `ibazel run :devserver` it doesn't recognize the tags.

/cc @gregmagolan

**Comment by achew22** [comment]
Is the expectation that ibazel would detect that it is a rule of type alias and then requery the actual or do you think this is a bug in the `blaze query` command?

**Comment by alexeagle** [comment]
I'm not sure - I've observed `alias` doing less than I would like in other situations too, so I would guess Bazel says this is WAI.

**Comment by achew22** [comment]
Agreed.

https://github.com/bazelbuild/bazel/issues/4205

**Comment by achew22** [comment]
I think this is an issue with Bazel, not us. If you think there is more to do please reopen.
