### ISSUE TITLE
Resource limit hit on OSX

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/bazel-watcher#101]
In order to get iBazel to work on OSX I needed to increase the resource limit for open files.

Used the approach suggested here: https://superuser.com/questions/827984/open-files-limit-does-not-work-as-before-in-osx-yosemite

> It seems like there is an entirely different method for changing the open files limit for each version of OS X!
> 
> For OS X Sierra (10.12.X) you need to:
> 
> 1. In Library/LaunchDaemons create a file named limit.maxfiles.plist and paste the following in (feel free to change the two numbers (which are the soft and hard limits, respectively):
> 
> <?xml version="1.0" encoding="UTF-8"?>  
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"  
>         "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">  
>   <dict>
>     <key>Label</key>
>     <string>limit.maxfiles</string>
>     <key>ProgramArguments</key>
>     <array>
>       <string>launchctl</string>
>       <string>limit</string>
>       <string>maxfiles</string>
>       <string>64000</string>
>       <string>524288</string>
>     </array>
>     <key>RunAtLoad</key>
>     <true/>
>     <key>ServiceIPC</key>
>     <false/>
>   </dict>
> </plist> 
> 2. Change the owner of your new file:
> 
> sudo chown root:wheel /Library/LaunchDaemons/limit.maxfiles.plist
> 3. Load these new settings:
> 
> sudo launchctl load -w /Library/LaunchDaemons/limit.maxfiles.plist
> 4. Finally, check that the limits are correct:
> 
> launchctl limit maxfiles

This works for OSX 10.13 (High Sierra), however I get warnings whenever running iBazel that look like this: `Warning: failed to raise resource limit 8 to 524288: Invalid argument`

Not sure what the best solution is. If a manual resource limit change on OSX is needed then perhaps it should be suggested in the README. From the warning above it seems that iBazel is attempting to increase the resource limit but failing?

There are also side-effects to increasing the resource limit manually as it may break other applications. Adobe Illustrator, for example, doesn't open up anymore for me with the error: `unable to set maximum number of files to be opened`.

**Comment by gregmagolan** [comment]
Also noticed this issue on fsnotify with no clear solution: https://github.com/howeyc/fsnotify/issues/89

**Comment by gregmagolan** [comment]
Ideal solution I think would be for iBazel to increase the resource limit if it is on OSX for the process when it starts up

**Comment by gregmagolan** [comment]
Just realized that the `Warning: failed to raise resource limit 8 to 524288: Invalid argument` comes from Bazel and not iBazel

**Comment by adamyi** [comment]
I have this problem as well. Is there an issue in the Bazel repo for this now?

**Comment by achew22** [comment]
This was fixed by #125
