### ISSUE TITLE
Leaking watchers will lead to resource exhaustion

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-watcher#11]
By creating watchers and not removing them we will inch closer to hitting the inode watcher limit. Normally this is in the neighborhood of 10k but it is not impossible that you would have a project near that limit and get to it with 8 hours of iteration.

Additionally we should detect when this limit is near (or reached) and notify the user how to fix it.

**Comment by achew22** [comment]
Reading more about inodes I think we can watch directories which should pretty dramatically cut down on the number of watchers we need. I think that's a better fix than maintaining and unwatching things until there are very very large projects that need it.

**Comment by ittaiz** [comment]
What do you lose?
Asking since I seem to remember Bazel advocating against passing
directories as inputs mainly since it's much more complicated (impossible?)
to know specifically what has changed in the folder

**Comment by achew22** [comment]
Directories (by which I assume you mean recursive globs) as inputs in Bazel are completely orthogonal to the concerns here. Bazel is still doing the dirty checking, iBazel is simply in charge of telling Bazel to "do stuff". So long as your BUILD files are well written there won't be any problems.

**Comment by achew22** [comment]
This was resolved in 291435d
