### ISSUE TITLE
Publish 0.3.0 to npm

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/bazel-watcher#110]
@achew22 Can you make a release that includes the profiler?

**Comment by achew22** [comment]
Blocked by https://github.com/bazelbuild/rules_go/issues/1238

**Comment by achew22** [comment]
I just pushed the v0.3.1 tag and released to NPM. Thanks for the push to do this.

https://github.com/bazelbuild/bazel-watcher/releases/tag/v0.3.1
https://www.npmjs.com/package/@bazel/ibazel
