### ISSUE TITLE
Usage instructions are unclear

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel-watcher#123]
I'm trying to use ibazel and the usage instructions are unclear

> Compile the //ibazel target inside this repo and copy the source file onto your $PATH.

There is no _source_ file that looks relevant and there is no output in the bin directory that is obvious like `bazel-bin/ibazel/ibazel`. There is `bazel-bin/ibazel/darwin_amd64_pure_stripped/ibazel` which I think is what I'm supposed to use.

**Comment by achew22** [comment]
I would love to get a PR. Send 'em in with your suggestions :smile:
