### ISSUE TITLE
-log_to_file redirects bazel's stderr in addition to ibazel's

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel-watcher#124]
I want to avoid the spam that ibazel outputs and it looked like -log_to_file is supposed to do that, except that it doesn't include stderr from bazel which I still want to get.

In particular log_to_file doesn't document that it redirects bazel's stderr as well, and if that is intentional seems like it offers very little/nothing over doing the redirection in the shell.

**Comment by achew22** [comment]
`-log_to_file` is a testing internal that is used in the e2e tests. It's existence is an implementation detail of the e2e testing.

Could you help me understand why you want to completely silence bazel output? I believe that would prevent there from being any usable UI to tell you what happened. What do I not understand?

**Comment by endobson** [comment]
I don't want to silence bazel, I want to silence ibazel. The majority of the lines that it outputs are not useful to me if it is working. They would be great for filing a bug report, but thats not the case most of the time.

All of the below are examples of where ibazel writes stuff that is not useful to me as someone who wants the output of bazel.

https://github.com/bazelbuild/bazel-watcher/blob/f09ef4ab16970522868f40aa7ef83c7946d22922/ibazel/ibazel.go#L258
https://github.com/bazelbuild/bazel-watcher/blob/f09ef4ab16970522868f40aa7ef83c7946d22922/ibazel/ibazel.go#L287
https://github.com/bazelbuild/bazel-watcher/blob/f09ef4ab16970522868f40aa7ef83c7946d22922/ibazel/ibazel.go#L289
https://github.com/bazelbuild/bazel-watcher/blob/f09ef4ab16970522868f40aa7ef83c7946d22922/ibazel/ibazel.go#L483

**Comment by endobson** [comment]
I don't have access to iblaze currently but my recollection is that it is much less verbose.


Here is the output from ibazel when a BUILD file changes when running `ibazel test //libraries:all`
```
State: WAIT
State: WAIT
State: WAIT
Build graph changed: "/Users/endobson/proj/racket/yaspl2/libraries/BUILD". Requerying...
State: DEBOUNCE_QUERY
State: DEBOUNCE_QUERY
State: DEBOUNCE_QUERY
State: DEBOUNCE_QUERY
State: QUERY
Querying for BUILD files...
Error watching file /Users/endobson/proj/racket/yaspl2/tools/defaults/BUILD
Error: lstat /Users/endobson/proj/racket/yaspl2/tools/defaults/BUILD: no such file or directory
Watching: 10 files
Querying for source files...
Watching: 134 files
State: RUN
Testing //libraries:all
```

Removing the state lines:
```
Build graph changed: "/Users/endobson/proj/racket/yaspl2/libraries/BUILD". Requerying...
Querying for BUILD files...
Error watching file /Users/endobson/proj/racket/yaspl2/tools/defaults/BUILD
Error: lstat /Users/endobson/proj/racket/yaspl2/tools/defaults/BUILD: no such file or directory
Watching: 10 files
Querying for source files...
Watching: 134 files
Testing //libraries:all
```

I think the "watching N files" is not useful to the user. It doesn't seem very actionable/informative to me, and I don't see a scenario where it's something I want to know.

The errors for the non existent file would be reasonable if those file were actual dependencies, so I don't think that ibazel should likely do anything about them (https://github.com/bazelbuild/bazel/issues/5052).

I don't think that the "Querying for ___ files" is useful as that is going to happen every time the build graph changes, and so is encompassed by the "Build graph changed "...". Requerying ..."line.

So my suggestion is to remove all of the 4 log lines I mentioned above. That would make it similar to the case when just a file is changed.

**Comment by achew22** [comment]
> I think the "watching N files" is not useful to the user. It doesn't seem very actionable/informative to me, and I don't see a scenario where it's something I want to know.

In my experience, both from watching people use the tool and doing it myself, it is helpful for detecting NFS detaches and broken build rules where the `srcs` has been wiped and you're not actually watching any files.

> I don't think that the "Querying for ___ files" is useful as that is going to happen every time the build graph changes, and so is encompassed by the "Build graph changed "...". Requerying ..."line.

When the program is starting up, without the "Querying for ___ files" line, the program would be completely silent and give you no notice that it is doing anything at all, let alone that it is doing something that can take north of 30 seconds in complex build graphs. That feels like a terrible user experience to me. How do you think we should approach that other than to tell the user that it is doing stuff?

**Comment by achew22** [comment]
The logging system has been rewritten and this is probably fixed now. Please reopen if there are more things you'd like
