### ISSUE TITLE
Support for passing flags to bazel is limited and undocumented

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel-watcher#126]
I want to pass flags to bazel such as `--cache_test_results=no` and `--test_output=streamed`. For some reason `--test_output` is supported but not `--cache_test_results`.

https://github.com/bazelbuild/bazel-watcher/blob/f3e920a9f07e26a7bf52e999c49302febae12d8c/ibazel/main.go#L28-L30

The fact that this is a supported feature is not documented, and so it is confusing for some flags to magically work and others to fail.

**Comment by achew22** [comment]
If you need any additional flags you can use '--' strategically to pass the flag down to bazel.

I believe `ibazel build -- --experimental_new_flag //path/to/target` should work. Would you like to send a quick PR (click the pencil icon and add in `--cache_test_results` along with the other flags you're interested in).

I would love to extract the set of flags from Bazel directly, but I can't think of a way to get them printed without invoking `bazel --help` and parsing the output which would be really slow. Can you help me come up with a better strategy than a hardcoded list that is always going to be incomplete? Maybe significant coverage by doing a one time dump is sufficient. WDYT?

**Comment by endobson** [comment]
The `--` is not documented for `test` only for `run` AFAICT (using the output of `ibazel`).

I'm not particularly interested in becoming a contributor of ibazel and instead just using it as a customer, as I do bazel. It seems that ibazel has much less resources dedicated to it (likely just you and on your spare time). If these bug reports sit around a long time before being fixed that is fine.

For this problem I think that it is fairly easy to distinguish between flags starting with '--' and target patterns which don't (AFAIK). Thus the syntax for ibazel could be `ibazel [ibazel-flag ...] command [target-pattern | flag] ...`.

I don't think it is important that ibazel not pass unknown flags to bazel if the user asks for it.

**Comment by yohcop** [comment]
I'm not sure this works entirely, especially when using run, and when I also want to pass flags to the binary being run. Something like:

```
ibazel run -- --experimental_new_flag //my/target -- binary_arg1 binary_arg2
```
I get:
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.handle(0xc420090a50, 0x7ffc94aafe64, 0x3, 0xc42000e0a0, 0x6, 0x6)
	ibazel/main.go:135 +0x2c6
main.main()
	ibazel/main.go:121 +0x236
```

Can I do something like this? Or escape the second -- maybe?

**Comment by achew22** [comment]
@IgorMinar Sorry you're not having any luck. it sounds like there might be a bug in that bit of code. In the meantime, feel free to send a PR to modify https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/main.go#L35 to add any flags you want.

**Comment by IgorMinar** [comment]
@achew22 done: #175

**Comment by girtsf** [comment]
I just ran into this as well.

Silly question and I'm probably missing something, but why not add anything that starts with "-" to args? Targets can't start with "-", right?

**Comment by achew22** [comment]
Yeah, I was wrong about this. There is an easy fix though. If you want to modify ibazel/main.go and add your flag to it then I'll build a release for you

**Comment by achew22** [comment]
I like your idea. I just tested out your theory with 

```
touch WORKSPACE && mkdir -- '--moo' && touch -- '--moo/run.sh' && chmod +x -- '--moo/run.sh' && echo 'sh_binary(name="--moo",srcs=["run.sh"])' > '--moo/BUILD' && bazel build -- ---moo
```

I think that means a target can start with a `-` or a `--`. This may be pathological though. I could be convinced that accommodating intentionally poorly named targets is a bad idea

**Comment by mariusgrigoriu** [comment]
PR for the `--nocache_test_results` #324 

After reading this, perhaps the PR should add `--cache_test_results=` instead. 

That all said, this whole flags business doesn't scale and another way to support the hundreds of possible flags should be devised.

**Comment by achew22** [comment]
@mariusgrigoriu I completely agree, do you have a theory on how it could be done and also preserve the ability to tack on additional flags at the end?

**Comment by mariusgrigoriu** [comment]
I brainstormed some ideas without filtering for quality and got:

1. ibazel flags are always the first argument
1. ibazel flags are non-overlapping with bazel flags and can be detected
1. ibazel or bazel flags are preceded with another flag, such as bazel's `--test_arg=`
1. ibazel executes bazel and parses output
1. ibazel connects to bazel server to request flags
1. Do not support any bazel arguments except for `--config=`. Users would need to pre-configure their .bazelrc with detailed flags
1. file watching is built into bazel instead of a separate wrapper
1. Somehow link against bazel to pull a list of flags

**Comment by achew22** [comment]
Unfortunately I think the best course of action here is probably going to be something along the lines of 8.

The e2e tests support invoking `bazel` in the context of a Bazel run. It seems theoretically possible to have some kind of `update_the_flags.go` that would include the system Bazel binary and run `bazel help --output=xml` (or similar), parse it out, and generate a list of flags.

Now to find cycles to actually do something like that.
