### ISSUE TITLE
Add support for http_archive

### ISSUE THREAD

**Issue by igorgatis** [bazelbuild/bazel-watcher#127]
I'd like to include bazel-watcher as a tool to my WORKSPACE. Idealy, I'd write something like:
```
http_archive(
    name = "com_github_bazelbuild_bazel_watcher",
    sha256 = "a3e878f862cbacb98611ee702cf4201796b9e9dd52b86621b571212725bf4a20",
    strip_prefix = "bazel-watcher-0.3.1",
    url = "https://github.com/bazelbuild/bazel-watcher/archive/v0.3.1.zip",
)
load("@com_github_bazelbuild_bazel_watcher", "bazel_watcher_dependencies")
bazel_watcher_dependencies()
```

**Comment by achew22** [comment]
How do you propose ibazel would be invoked in this scheme?

**Comment by asf-stripe** [comment]
I'd love to have this too. I imagine it would be possible (with an appropriate rules file and macro definition to pull the correct deps into a project's WORKSPACE) to get ibazel running with: `bazel run -- @bazel-watcher//ibazel:ibazel -- arg1 arg2 arg3`

**Comment by achew22** [comment]
Out of curiosity, have you tried this since https://github.com/bazelbuild/bazel/issues/2337 was closed? I think this might "just work"(tm)

**Comment by achew22** [comment]
I'm going to close this since I think it is fixed. Please reopen if you keep experiencing it.
