### ISSUE TITLE
undefined: js when trying to build it

### ISSUE THREAD

**Issue by GeertVL** [bazelbuild/bazel-watcher#132]
When I try to compile I get the following error:

**profiler\profiler.go:339:21: undefined: js**

In the code it looks like this:

```	rw.Header().Set("Content-Type", "application/javascript")
	_, err := rw.Write(js)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error handling profile.js request: %v\n", err)
	}
```
And js is nowhere declared or referenced. What am I missing?

**Comment by achew22** [comment]
How did you compile the binary? Did you `bazel build` it or `go get` it? Can you try using the other system if you only tried one?

**Comment by GeertVL** [comment]
No in Jetbrains Goland. I am trying to get it working on Windows. I fixed most issues already with the difference between Windows and Linux. But what I found out is that based on the profile.js file it creates a var js := "...";

But that does not happen in Jetbrains Goland ofcourse it happens during the Bazel build and not when I want to debug in Goland or how do I do it best?

**Comment by achew22** [comment]
If you want to just use it for testing you could copy the generated `.go` file into that directory, then you should be able to access the `js` variable. Does that work?

**Comment by GeertVL** [comment]
That did the trick. Pure out of curiosity. How do you debug? With Bazel?

**Comment by achew22** [comment]
I prefer test cases to ad hoc testing and I do that with `ibazel test //...`

**Comment by GeertVL** [comment]
Thank you I will try it that way to get it working on Windows.
