### ISSUE TITLE
Correct order of stdout/stdin

### ISSUE THREAD

**Issue by hdt91** [bazelbuild/bazel-watcher#136]
Hi,

I am writing a simple wrapper of the `bazel` package and would like to check if the swapped order of `stdoutBuffer`/`stderrBuffer` was intended in the command initialisation code [here](https://github.com/bazelbuild/bazel-watcher/blob/master/bazel/bazel.go#L94-L103)? Thank you.

**Comment by achew22** [comment]
Nope. That was a mistake. If you would like to send a PR it would be greatly appreciated. Thanks!
