### ISSUE TITLE
Second and further file changes not detected on MacOS Mojave

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel-watcher#173]
Possibly related to https://github.com/bazelbuild/bazel-watcher/pull/139 and https://github.com/angular/angular/issues/21770

I've tested this using bazel-watcher version 0.7.0 and 0.5.0, on MacOS Mojave.
As an example project I picked `java-tutorial` from https://github.com/bazelbuild/examples.git .
Checkout that repository, change into the `java-tutorial` directory and execute `ibazel build //:ProjectRunner`. Then open the files `src/main/java/com/example/{Greeting.java,ProjectRunner.java}` in an editor.
- Enter an empty line into the first file and save.
    `ibazel` notices and rebuilds the target.
- Enter a second empty line into the first file and save.
    `ibazel` does not notice the modification and does not rebuild the target.
    Any further edits to this file are not noticed.
- Enter an empty line into the second file and save.
    `ibazel` notices and rebuilds the target.
- Enter a second empty line into the second file and save.
    `ibazel` does not notice the modification and does not rebuild the target.
    Any further edits to this file are not noticed.

We have observed the issue on two separate MacOS Mojave machines. We have observed it with version `0.5.0` and `0.7.0`. We have not seen an instance of `ibazel` working properly on MacOS.

---

**Update**: The issue was observed on MacOS Sierra (10.12.6) and Mojave (10.14).
The issue was not observed on Linux, bazel-watcher seems to be working fine on Linux.

**Comment by achew22** [comment]
The real problem is that I don't have a Mac to debug with. Any ideas/information you have is a thing I would be very happy to help with, I just don't have a box to test on :frowning_face:

**Comment by aherrmann** [comment]
@achew22 FreeBSD might be a good alternative as a development platform. It also uses kqueue and you can run it in a VM. At a glance it seems like Bazel and fsnotify support FreeBSD.

**Comment by aherrmann** [comment]
Awesome, thanks @dougkoch and @achew22 . I tested this on a Mojave machine and the issue seems to be fixed. :tada:

**Comment by achew22** [comment]
Woohoo! I'm cutting a v0.8.0 release right now.
