### ISSUE TITLE
ibazel_notify_changes not working for tests

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-watcher#184]
I am trying to implement something very similar to https://github.com/bazelbuild/rules_nodejs/pull/233 for a nodejs test rule and not getting it to work with the `ibazel_notify_changes`. It is really strange if I take my rule, make it a binary then it all works fine and I can listen to stdin for the ibazel messages as expected. As soon as I turn the rule into a real test via the `test=True` attribute and a `_test` name things start failing and the binary seems to be getting a `close` event sent pretty quickly (when listening to stdin) and then never gets the message from ibazel passed on on rebuild. Maybe there are some test limitations (and I have tried running the test with just `bazel run`)?

I have spent a few hours investigating but could not find anything so far.

**Comment by achew22** [comment]
Do you have any more specifics? Maybe a test repo that I could play with to diagnose?

**Comment by Globegitter** [comment]
Yes, apologies it was late when I posted this. Here you have a repro: https://github.com/ecosia/bazel_rules_nodejs_contrib/tree/jest-rules

If you run `ibazel run //examples/nodejs_jest_test:sum_test` that runs the test using the test rule and you can see that `ibazel stream closed` logs immediately and changes to `sum.test.js` trigger nothing in the binary. But if you run `ibazel run //examples/nodejs_jest_test:sum_test.binary` (which is exactly the same as the test rule, just the test attributes removed for demonstration purposes) then you see things working as expected, changing e.g. `sum.test.js` logs `IBAZEL_BUILD_COMPLETED SUCCESS` printed by the test binary after reload.

**Comment by achew22** [comment]
This seems very odd to me. Would you be willing to duplicate a testcase in the e2e tests that exercises this? Here is [an example](https://github.com/bazelbuild/bazel-watcher/blob/master/e2e/live_reload/live_reload_test.go#L67) I think just creating an extra `must(t, b.ScratchFile("defs.bzl", "# some code in here that creates a very simple rule that has test turned on"))` and modifying the BUILD file  would be enough to determine if it is an iBazel issue or something in your repo. Does that work for you? There is a LOT of stuff going on in `rules_nodejs` +  `bazel_rules_nodejs_contrib` and even with a few hours of mucking in it over the past few weeks, I don't think I quite understand what is happening in a clear way. Having a self-contained example of this bug would be really helpful to me.

**Comment by Globegitter** [comment]
@achew22 Yep I understand that a lot is happening in that repo, happy to add a e2e test for it as soon as I get around to it.

**Comment by achew22** [comment]
@Globegitter did you ever get a chance to look into this? I would love to find the bug and squash it but I need a little help

**Comment by achew22** [comment]
Gah! Enter is so easy to accidentally git.

... I need a little help finding it. Is this still happening? Do you have any more clues on what's triggering it?

**Comment by Globegitter** [comment]
@achew22 Sorry I dropped the ball on this. I will create a more minimal example this week.

**Comment by Globegitter** [comment]
@achew22 sorry about taking such a long time. While I would still like to write the e2e test at least I managed to write a simple repro case now: https://github.com/Globegitter/bazel-watch-test-repro

Let me know if that is a sufficient simple repro case.

**Comment by DavidANeil** [comment]
I believe that https://github.com/bazelbuild/bazel/pull/8322 will fix this.

**Comment by achew22** [comment]
@DavidANeil did that fix the issue?

**Comment by DavidANeil** [comment]
I didn't test any of the repros provided here or in that issue, but the merge did fix our case and we are able to successfully use `ibazel_notify_changes` with `_test` executables now.

Basically: yes I'm pretty sure this issue should be closed, but I haven't done due diligence.

**Comment by achew22** [comment]
Okay, I'm going to close this, but if someone else runs into it please open a new one or reopen this.

Thanks everyone!
