### ISSUE TITLE
ibazel should not crash if a build file change results in a syntax error

### ISSUE THREAD

**Issue by IgorMinar** [bazelbuild/bazel-watcher#194]
given `ibazel test //foo/bar`

if I make a typo in `foo/bar/BUILD.bazel`

ibazel process crashes and prints out the underlying bazel error

I expect the watcher to display the error, but keep on watching the same files as before. It's likely that the next file change will correct the build error and I'll be able to run the tests again.

The current behavior breaks the development flow and creates significant ergonomics issue for anyone using ibazel.

**Comment by achew22** [comment]
@IgorMinar is the behavior:

1.  Valid `foo/bar/BUILD.bazel`
1. Invoke `ibazel test //foo/bar/BAZEL.BUILD` (success)
1. Write *invalid* `foo/bar/BUILD.bazel`
1. `ibazel` runs automatically and crashes

**Comment by IgorMinar** [comment]
@achew22 correct
