### ISSUE TITLE
How do we test if output_runner is reading the output correctly

### ISSUE THREAD

**Issue by borkaehw** [bazelbuild/bazel-watcher#196]
`output_runner` was introduced few months ago, which is a good feature. We recently rebased iBazel from master but `output_runner` is broken because of https://github.com/bazelbuild/bazel-watcher/commit/add8041bfb843d5566e18b6711d88e4e10c5b699. The test for `output_runner` is not sufficient since we are not testing if `output_runner` can correctly read the log from Bazel.

My question is what is the best way to run a Bazel command in Bazel test to simulate there is a dependency issue and `buildozer` command is generated? And we should run the `buildozer` command in Bazel test to see if `output_runner` can fix the `BUILD.bazel` correctly, if possible.

**Comment by achew22** [comment]
@borkaehw, thanks for fixing the issue earlier today. I've added a light e2e test that validates the current functionality. If you want to expand on the tests that I have in #198 it would be greatly appreciated. I'm happy to help in any way necessary, feel free to ask.

PS: Sorry about breaking you! These e2e tests are really good at preventing breakages, but they have to exist first. Hopefully this won't happen again.

**Comment by borkaehw** [comment]
Thanks for tackling this issue so fast. The PR looks great at the first glance, I will take a deeper look later today. If it catches the issue and CI passes, that's all we want and feel free to merge it.
