### ISSUE TITLE
When initial build fails, ibazel should exit

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#2]
$ ibazel build //example:all
Error running Bazel exit status 7
Building //example:all
Files changed rebuilding...
ERROR: while parsing '//example:all': no such package 'example': BUILD file not found on package path.
INFO: Elapsed time: 0.182s
Build error: exit status 1     
[ tool is now apparently hung ]

I think it's better to exit in this case (like iblaze does)

**Comment by achew22** [comment]
I've several times found myself writing `while true; do iblaze build $target; done` in order to try and fix up some vexing syntax errors (usually error prone yelling at me :wink:). What would you think about bailing if the query fails but not if the build/test/run fails?

**Comment by alexeagle** [comment]
True, I've also found the asymmetry of bailing out after a failed build annoying. @mprobst do you have a strong case for that behavior?

**Comment by mprobst** [comment]
I think this should only fail if the query fails (i.e. if bazel-watcher doesn't know what to watch).

**Comment by alexeagle** [comment]
Here's a confusing case: I do
`ibazel run :devserver`
and there is a compile error. My devserver is not started. But, ibazel is still running.
Now I fix the compile error, ibazel reports success. But the devserver is still not running.

It feels like either ibazel should exit if first build is not successful, or else `ibazel run` should have a special case that it starts the binary on the first successful build.
