### ISSUE TITLE
output_runner multiline regex and env variable support

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-watcher#206]
I am running into two issues with the output_runner (which otherwise works great btw!). One it does currently not support multiline regex. So e.g given an error string of

```
GoCompile: missing strict dependencies:
	/home/markus/.cache/bazel/_bazel_markus/c83dd5dc66625baf386a59b750f50a10/path/__main__/app/api_proxy.go: import of "github.com/gregjones/httpcache"
```

I want to check for `GoCompile: missing strict dependencies` to be in the string but also get the path after the `__main__` on the next line, to be able to use it in the args. But since currently the logic goes line-by-line: https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/output_runner/output_runner.go#L117 that is not possible

The second one is, rather then executing a command directly, I want to execute it based on an environment variable that is set, so `"command": "$COMMAND",` but because of the logic here: https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/output_runner/output_runner.go#L132 it replaces the string with anything it found with the `FindStringSubmatch`.

This should not be very big things and I know the code base that I could do this myself now, just wanted to have it tracked here because I am not sure when I will get to it.

cc @borkaehw

**Comment by achew22** [comment]
As a short term fix you could set it to run `gazelle` when you detect the string `GoCompile: missing strict dependencies:`. That's what I do in my projects and it seems to work well.

**Comment by Globegitter** [comment]
I am worried about time growing as our monorepo grows and also there being a chance of unrelated files getting touched (as we are currently not enforcing buildifier in any way, which to be fair we should probably be doing). That is the main reason for this request, but agreed that is what I will do in the meantime.

**Comment by achew22** [comment]
@Globegitter I've been delinquent on bug triage (sorry). Is this still an issue?

**Comment by Globegitter** [comment]
@achew22 as long as I used bazel in my previous job it still was an issue, so I would expect this still to be valid.
