### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-watcher#207]
It looks like bazel-watcher doesn't work with `--incompatible_no_transitive_loads` (https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/77#f40ae254-2c70-412d-9e4e-3ea30a72b6cf).

Can you please fix it?
(at the same time, you may want to try other incompatible flags)

**Comment by philwo** [comment]
Friendly ping @achew22

**Comment by achew22** [comment]
@philwo, unfortunately this blocked by Bazel integration testing.

```
ERROR: D:/b/oeuyfwbx/external/com_github_bazelbuild_bazel_integration_testing/tools/repositories.bzl:15:1: file ':common.bzl' does not contain symbol 'BAZEL_HASH_DICT'
```

Lemme see if there is an issue over there that matches this

**Comment by philwo** [comment]
Glad that it worked out - thanks for fixing it!
