### ISSUE TITLE
Full log not being shown on initial querying

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-watcher#217]
If I run e.g. `bazel test //app/...` and the cache is not filled I can see things like

```
INFO: Invocation ID: a7782439-9243-4dbe-8277-69ebcb8f7e97
16:12:15) INFO: Build option --define has changed, discarding analysis cache.
(16:12:16) Analyzing: 57 targets (1 packages loaded, 8182 targets configured)
    Fetching @go_image_base; fetching
...
```

where-as if I run `ibazel test //app/...` I only see

```
Querying for files to watch...
(16:15:52) INFO: Current date is 2019-02-18
(16:15:52) Loading: 0 packages loaded
...
```

Specifically the `Fetching @go_image_base; fetching` is not being shown, which makes the whole thing feel a bit strange as almost nothing is happening as the packages are being loaded and if that image downloads e.g. takes 100s that is quite a long time where things just "seem stuck". I think it would be nice to see the logs of the fetching as well or at least have a flag to be able to turn this on.

**Comment by Globegitter** [comment]
Having dug around a bit, it seems the issue is somewhere around here: https://github.com/bazelbuild/bazel-watcher/blob/master/bazel/bazel.go#L100, if I change `b.cmd.Stderr = io.MultiWriter(os.Stderr, stderrBuffer)` to `b.cmd.Stderr = os.Stderr` then I can see the `Fetching ...` logs. Whenever it refreshes it shows the log on a new line rather than replacing, so you see

```
(16:38:35) Loading: 0 packages loaded
(16:38:36) Loading: 0 packages loaded
    Fetching @go_image_base; fetching
    Fetching @go_debug_image_base; fetching
(16:38:37) Loading: 0 packages loaded
    Fetching @go_image_base; fetching
    Fetching @go_debug_image_base; fetching
(16:38:38) Loading: 0 packages loaded
    Fetching @go_image_base; fetching
    Fetching @go_debug_image_base; fetching
```

but still a step forward, at least one can see that something is going on.

**Comment by achew22** [comment]
@Globegitter sorry for an extremely slow response. Is this still happening? can you help me create a reproduction? Is there any circumstance where it is more/less likely to work?

**Comment by Globegitter** [comment]
@achew22 Sorry for the late response on my side now, I switched jobs and not using bazel for my job longer - but in any case, as far as I remember that happened for any run that had to download external repositories. And it is being made more obvious if one has to download e.g. big docker images to run some tests, as that can take some time.
