### ISSUE TITLE
Get all tests passing with --incompatible_disable_legacy_cc_provider for Bazel 0.25.0

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel-watcher#223]
It seems that bazel-watcher will start breaking with the next Bazel release 0.25 because of an incompatible change (https://github.com/bazelbuild/bazel/issues/7036)

`ERROR: /private/var/tmp/_bazel_buildkite/454a0bdac88b8440a1c43b58bde36aa3/external/org_golang_x_sys/unix/BUILD.bazel:3:1: in libs attribute of _cgo_collect_info rule @org_golang_x_sys//unix:go_default_library%android_arm%cgo_info: '@org_golang_x_sys//unix:go_default_library%android_arm%cgo_c_lib' does not have mandatory providers: 'cc'. Since this rule was created by the macro 'go_library_macro', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_buildkite/454a0bdac88b8440a1c43b58bde36aa3/external/io_bazel_rules_go/go/private/rules/cgo.bzl:694:16`

I don't see any errors for rules_go, so it could be that bazel-watcher is using an old version of rules_go?

**Comment by achew22** [comment]
@oquenchil, looks like you're right. I should update to rules_go 0.18. I thought I had renovatebot set up to mail me PRs that do that automatically when a new one is released. Do you have any idea what happened to that?

**Comment by oquenchil** [comment]
Sorry Andrew, I don't know how renovatebot works and I have no idea what could have gone wrong there. I just caught this because it showed in our CI.

Thank you for updating!

**Comment by achew22** [comment]
I believe this is fixed now. Thanks for keeping up on it. If it isn't fixed, please reopen
