### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-watcher#224]
Based on our latest CI run (https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/31#8be23668-875f-4589-8553-c24684fa5f80), migration is needed for the following flags:
  * --incompatible_disable_deprecated_attr_params
  * --incompatible_disable_legacy_cc_provider
  * --incompatible_disable_legacy_proto_provider
  * --incompatible_no_support_tools_in_action_inputs

Could you take a look at this?

**Comment by achew22** [comment]
@laurentlb, I just updated all my dependencies and I believe that should fix all the flags. Can you check the latest run and tell me if it is still an issue?

**Comment by laurentlb** [comment]
With `--incompatible_no_support_tools_in_action_inputs`, I see an error in rules_go. But rules_go at head is working fine with the flag.
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/36#db28e8c0-5b35-4db6-b7a4-3b474e2e7530

Your WORKSPACE file is using rules_go 0.18 which was released two days ago. So it's obviously up-to-date.
Due to the way WORKSPACE files work, it's possible another dependency is pulling an old version of rules instead. I suspect we need to update something else in another repository first.

**Comment by achew22** [comment]
I think that RenovateBot (or something like it) will make this a lot easier going forward. Thanks so much for following up!
