### ISSUE TITLE
File changes beyond the first are not detected on Windows 10

### ISSUE THREAD

**Issue by zaucy** [bazelbuild/bazel-watcher#236]
Tested on latest master (commit at time of writing = 01bdaa8d8629a60ba5ab1b62b6ddb67c8cc0d00b). May affect other platforms, but I have only tested on Windows 10.

This change fixes my issue: https://github.com/zaucy/bazel-watcher/commit/d8eb7cd3e5f1d7459af6e21b14f49f971587aa0d

I didn't want to make a pull request because I am not that familiar with go or fsnotify to understand why this works. Can anyone chime in?

**Comment by achew22** [comment]
@zaucy, first off thanks for the issue report! It looks like there must be a bug in `source_event_handler.go` given the error conditions you describe

* Does this consistently happen?
    * If so what percentage of the time?
* Would you be willing to help debug things a little bit more by running a few commands and possibly compiling/running a binary to pull fsnotify events?
* What version of Windows 10 are you running?

Thanks!

**Comment by zaucy** [comment]
> Does this consistently happen?
Yes 100% of the time

> Would you be willing to help debug things a little bit more by running a few commands and possibly compiling/running a binary to pull fsnotify events?
Yep absolutely

> What version of Windows 10 are you running?
Windows 10 Pro 10.0.17763 Build 17763

**Comment by zaucy** [comment]
I don't know what/where anything has changed, but I haven't had this issue for awhile now so I'm going to close it.
