### ISSUE TITLE
Add option to ignore files to be watched

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-watcher#244]
This came from a discussion with @alexeagle about macos performance issue when working with Angular because too many files are being stat'ed. One suggestion was to add the option to explicitly ignore some paths from being watched. This issue is just to track this publicly but also get the discussion started on what a best implementation of this would look like.

I can think of three options, either one could automatically add paths from `.bazelignore`, which would be nice, to not have to add yet another file but on the flipside, maybe it is bad design to couple these behaviours as they might not have a 1:1 mapping. The other two would be to add a `.ibazelignore` or a flag, like `ibazel -ignore-paths`. 

For the case of node_modules having some persisted way to ignore that is probably nice, but happy to get some more input on this.

**Comment by alexeagle** [comment]
yeah in our case `.bazelignore` is for the `node_modules` directory in the users project, but the inputs we want ibazel to not bother watching are in `external/npm/node_modules`

Maybe it's simply a matter that ibazel is watching files in external workspaces, and shouldn't?

**Comment by achew22** [comment]
Unless I've completely forgotten how it works, I don't think ignore will achieve what it is you want. The watcher queries for files that are depended on by the specified targets and then adds watchers for the directory that contains them in your workspace. It shouldn't traverse the boundary into external at all and now that it only watches the directory then performs filtering, it shouldn't be watching very much stuff at all.

Could I have you add a log statement to https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/ibazel.go#L491 to see how many/what things it is watching? Do you have a repo that exhibits this behavior? What version of iBazel are you running?
