### ISSUE TITLE
ibazel run on container_image does not work

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-watcher#245]
I have a container_image like follows:

```
container_image(
    name = "image",
    base = "@nginx_alpine//image",
    directory = "/etc/nginx/",
    docker_run_flags = "--rm -it -p 8080:8080",
    files = [
        "nginx.conf",
    ],
    legacy_run_behavior = False,
)
```

and all works well when doing `bazel run :image`, it starts the image, i can CTRL+C out of it etc. but when using `ibazel run` I am getting the error message from docker:

```
the input device is not a TTY
```

By removing either the `-i` or `-t` in the `docker_run_flags` I can get around the error message but then pressing CTRL+C does not actually stop the docker container and on rebuild then it complains that the port is already allocated.

Not sure if there is an easy way to fix this and also happy to investigate myself (though will not happen in the next weeks) but wanted to make sure it is tracked.

**Comment by statik** [comment]
I just ran into this as well - would love to migrate my project off of docker compose and ibazel run of container targets would be just the ticket.

**Comment by achew22** [comment]
Sounds like a great opportunity for a first PR. How can I help you with that?

**Comment by statik** [comment]
I'm happy to try and narrow down the issue, I think the first step would be for me to make a little standalone repo that illustrates the problem, and then it will take some investigating to try and narrow down why the process is not getting killed.

**Comment by Globegitter** [comment]
@statik My experience with this sort of thing has been that there is an issue with correct signal propagation. I have ran into a similar issue in the past with rules_nodejs where they wrapped all binaries in a shell script. So it could be a similar issue here. Not sure about the TTY error message though, I do not remember seeing that in the case of rules_nodejs.

**Comment by statik** [comment]
I made a test case here: https://github.com/kindlyops/bazel-cross-docker

Need to do some checking to see what signals are making it through.

**Comment by achew22** [comment]
@statik did you have any luck diagnosing which signals were getting eaten?

**Comment by statik** [comment]
@achew22 no, I haven't been able to make any progress with debugging unfortunately.

**Comment by vanils** [comment]
@statik @achew22 The issue seems to be ibazel sending `SIGKILL` to terminate a process on Unix. In case of Docker this doesn't work well. `SIGKILL` simply kills the Docker CLI giving no chance to proxy any signals to the container which is therefore left up and running. As a result there is _the port already allocated_ error when attempting to start a server without stopping the previous instance of it.

A small discussion about `SIGKILL` not stopping a Docker container: https://github.com/moby/moby/issues/35647.

Changing `SIGKILL` to `SIGTERM` fixes this issue for me on MacOS. I believe the same works on Linux. I'm not sure if the problem exists on Windows in the first place due to differences in how processes are started and stopped - I haven't tested yet.

Changing the default kill signal from `SIGKILL` to `SIGTERM` might break some existing project setups? How about giving an ability for user to specify which signal to use for process termination. Maybe a flag like `--signal` which would default to `SIGKILL`? This flag would useful in general as for example `SIGTERM` would give application an ability to gracefully shutdown before a restart. The flag would probably have to be Unix specific as I believe Windows doesn't support signals.

If this idea sounds good I'm happy to make a PR. I'll have to admit: debugging this issue is literally all that I have as an experience with go, but I believe I can manage a simple change like this.

**Comment by statik** [comment]
@vanils thanks for figuring this out! I'd be very happy to help with testing a PR.

**Comment by achew22** [comment]
> Changing the default kill signal from SIGKILL to SIGTERM might break some existing project setups? How about giving an ability for user to specify which signal to use for process termination. Maybe a flag like --signal which would default to SIGKILL? This flag would useful in general as for example SIGTERM would give application an ability to gracefully shutdown before a restart. The flag would probably have to be Unix specific as I believe Windows doesn't support signals.

I agree that windows doesn't support signals. We have a different implementation of subprocesses for windows so I don't think there will be interference. 

The only issue to consider here is, what if the subprocess doesn't shut down from a `SIGTERM`. If the process is caught in a deadlock then the user will bail out of ibazel with `ctrl-c` a couple of times and then ibazel will `os.Exit` leaving an orphan process holding the ports open.

In the [signals handler](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/ibazel.go#L142) code we already handle the various cases of this. What would you think about sending a `SIGTERM` on the first attempt then a `SIGKILL` on future ones?

>If this idea sounds good I'm happy to make a PR. I'll have to admit: debugging this issue is literally all that I have as an experience with go, but I believe I can manage a simple change like this.

Seems to me like you're doing great then!

**Comment by vanils** [comment]
> I agree that windows doesn't support signals. We have a different implementation of subprocesses for windows so I don't think there will be interference.

Then leaving Windows out of this is probably the way to go.

> The only issue to consider here is, what if the subprocess doesn't shut down from a SIGTERM. If the process is caught in a deadlock then the user will bail out of ibazel with ctrl-c a couple of times and then ibazel will os.Exit leaving an orphan process holding the ports open.

Agreed. Hitting ctrl-c should have some special behavior to handle a deadlock situation. `SIGKILL` might still leave something open (as in case of a Docker daemon), but at least user can escape ibazel cli. In other cases `SIGKILL` probably does the trick and terminates everything.

> In the signals handler code we already handle the various cases of this. What would you think about sending a SIGTERM on the first attempt then a SIGKILL on future ones?

Idea sounds good to me. To be more specific: how about initially using `SIGTERM` (or what ever signal user provided as `--signal`), wait for x amount of time and if process doesn't terminate, ask for user to press ctrl-c again which would then send `SIGKILL`. The flow from then on would work the same way as currently - yet another ctrl-c proceeds to `osExit`. So extra step in the middle in case of hanging process.

Maybe it would be best to limit this `SIGKILL` fallback only to ctrl-c? As user I would find it unexpected that ibazel uses some other signal as one provided by `--signal` during a restart. It might also conflict with what ever timeouts and fallbacks user have implemented on application side.

**Comment by achew22** [comment]
> Agreed. Hitting ctrl-c should have some special behavior to handle a deadlock situation. SIGKILL might still leave something open (as in case of a Docker daemon), but at least user can escape ibazel cli. In other cases SIGKILL probably does the trick and terminates everything.

I presume we can check the liveness of a subprocess (citation needed). If that's the case what would you think about giving the process a small number of seconds to die before killing it forcefully as another implementation option?

**Comment by mmehtonen-shpra** [comment]
> I presume we can check the liveness of a subprocess (citation needed). If that's the case what would you think about giving the process a small number of seconds to die before killing it forcefully as another implementation option?

Would it cause confusion if ibazel automatically sends `SIGKILL` without any action from a user if they specifically requested some other signal? In some cases there would be things left behind (like in this case with a Docker daemon - `SIGKILL` would leave a container running). Also timing might be hard to balance perfectly. Waiting too little and ibazel might prematurely kill a slower normally functioning graceful shutdown. Waiting too long and it would be annoying to users.

> In the signals handler code we already handle the various cases of this. What would you think about sending a `SIGTERM` on the first attempt then a `SIGKILL` on future ones?

Actually I'm starting to lean towards this option. The first ctrl-c sends a signal provided by the user. The second ctrl-c would send `SIGKILL` if termination of the first ctrl-c haven't been completed. If `SIGKILL` is used, it might be best to inform user with some sort of log message. Hitting ctrl-c after succesful termination either by user provided signal or `SIGKILL` would cause `osExit`.

This would be simple. It would support user repeately hitting ctrl-c to quickly shutdown everything while being informative and giving the user the decision whether to use `SIGKILL`. Also the implementation would be pretty easy I think.

What do you think?

**Comment by vanils** [comment]
> I presume we can check the liveness of a subprocess (citation needed). If that's the case what would you think about giving the process a small number of seconds to die before killing it forcefully as another implementation option?

Would it cause confusion if ibazel automatically sends `SIGKILL` without any action from a user if they specifically requested some other signal? In some cases there would be things left behind (like in this case with a Docker daemon - `SIGKILL` would leave a container running). Also timing might be hard to balance perfectly. Waiting too little and ibazel might prematurely kill a slower normally functioning graceful shutdown. Waiting too long and it would be annoying to users.

> In the signals handler code we already handle the various cases of this. What would you think about sending a `SIGTERM` on the first attempt then a `SIGKILL` on future ones?

Actually I'm starting to lean towards this option. The first ctrl-c sends a signal provided by the user. The second ctrl-c would send `SIGKILL` if termination of the first ctrl-c haven't been completed. If `SIGKILL` is used, it might be best to inform user with some sort of log message. Hitting ctrl-c after succesful termination either by user provided signal or `SIGKILL` would cause `osExit`.

This would be simple. It would support user repeately hitting ctrl-c to quickly shutdown everything while being informative and giving the user the decision whether to use `SIGKILL`. Also the implementation would be pretty easy I think.

What do you think?
