### ISSUE TITLE
--test_env argument not in allowed list

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/bazel-watcher#256]
The [`--test_env`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_env) argument is not in your `overrideableBazelFlags`, meaning it gets passed into Bazel as a target when running `ibazel test --test_env=blah=blah //some:test`

You may want to also consider adding the following (although it is not an exhaustive list):
- `--action_env`
- `--repo_env`
- `--stamp`
- `--nostamp`
- `--test_timeout`
- `--runs_per_test`

**Comment by achew22** [comment]
It should be pretty easy to add a new flag to the list by editing t[his file](https://github.com/bazelbuild/bazel-watcher/blob/b09eca820d952270473e67aeda9c08fe1327676b/ibazel/main.go#L27) and it would be a great first PR. I'll even do a release if you send it in 😉

**Comment by achew22** [comment]
I just released this on github and NPM so you should be good to go now. Thanks so much for your contribution!
