### ISSUE TITLE
Link error  "-pie and -r are incompatible"

### ISSUE THREAD

**Issue by genehwung** [bazelbuild/bazel-watcher#26]
..../external/org_golang_x_sys/unix/BUILD.baze
bazel build ibazel:ibazel. Got link error:
l:3:1: Linking ../org_golang_x_sys/unix/go_default_library.cgo.dir/_all.o failed (Exit 1)
/usr/bin/ld.gold: fatal error: -pie and -r are incompatible
collect2: error: ld returned 1 exit status

Environment info
Ubuntu 17.04
bazel version 0.5.4

When reverse the go build rule to 0.5.2, it worked.

**Comment by achew22** [comment]
This sounds to me like it is probably an issue in rules_go. To confirm this can you try running `bazel build //your:target`? If it has the same error then it's a problem with rules_go. Please reopen if that isn't the case.

**Comment by gonzojive** [comment]
The relevant rules_go issue is here:
https://github.com/bazelbuild/rules_go/issues/252
