### ISSUE TITLE
Give output runner an option to exit early

### ISSUE THREAD

**Issue by DavidANeil** [bazelbuild/bazel-watcher#260]
Sometimes the build will output 100+ errors but the fix for the first will fix all 100+ of them.
Currently with output_runner, the fix will be applied from the first error, and then for all of the other errors the tool may try to fix the issue, but the issue is likely already resolved from the first fix.  Not only can this cause issues with certain tools, but can also cause massively increase the time to complete a build.

I think there are two reasonable solutions to this:
1) If the "command" specified in `.bazel_fix_commands.json` returns a specific error code then immediately dump any existing output and restart the build.
2) Add an option to `.bazel_fix_commands.json` that specifies that a match should only be applied once per build.

**Comment by achew22** [comment]
@DavidANeil we left things at adding some documentation in PR #262 . Is this still of interest to you?

**Comment by DavidANeil** [comment]
I think there is consensus that no-one wants this currently.  Closing.
