### ISSUE TITLE
Color output in console can conflict with output_runner regex

### ISSUE THREAD

**Issue by DavidANeil** [bazelbuild/bazel-watcher#263]
It would probably be best to have output_runner strip any color codes from the output before trying to match the regex.

**Comment by achew22** [comment]
@DavidANeil, the idea here, I presume, would be to strip [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) and just pass it through? Do you have any sample input and output pairs?

**Comment by DavidANeil** [comment]
Yes, I believe removing those escape codes would be the most general solution.

I am seeing output from rules_typescript that looks like:
`[96mpath/to/my/file.ts[0m:[93m1[0m:[93m48[0m - [91merror[0m[90m TS2307: [0mCannot find module 'library/file'.`
Which I am currently matching using the regex `(\\x1B\\[96m)?(.*?\\.ts).*?(\\x1B\\0m)?:(\\x1B\\[93m)?\\d+(\\x1B\\[0m)?:(\\x1B\\[93m)?\\d+(\\x1B\\[0m)? - (\\x1B\\[91m)?error(\\x1B\\[0m)?(\\x1B\\[90m)? TS2307: (\\x1B\\[0m)?Cannot find module '(.*?)'\\.`

For my use cases the regex simply replacing `/\x1B\[\d*?m/g` with nothing would work for the colors, I'm not sure but I think `/\x1B\[[0-9;]*[mGKHF]/g` would match all of the escape codes.

I also added a `.*?` because I was sometimes seeing a backspace character being output as well.  Would it make sense to also remove those?
