### ISSUE TITLE
run command should also forward recognized flags

### ISSUE THREAD

**Issue by zoido** [bazelbuild/bazel-watcher#269]
As mentioned in the <https://github.com/bazelbuild/bazel-watcher/issues/242#issuecomment-478871815> run does not forward `overrideableBazelFlags` to the `bazel run` command.

https://github.com/bazelbuild/bazel-watcher/blob/18bdb44832ccc533e0ab3923ef80060eeb24582d/bazel/bazel.go#L210

This can be really useful for running watcher on binaries in dev mode like

```sh
ibazel run --config=dev //cmd/server

**Comment by achew22** [comment]
@zoido, this seems like a really great first PR. Do you think you could take a stab at it? It would be really great to add an e2e test to confirm functionality as well. How could I help you with that?
