### ISSUE TITLE
Add support for bazelrc flag

### ISSUE THREAD

**Issue by libsamek** [bazelbuild/bazel-watcher#278]
Since there are only a few Bazel flags supported, it would be really useful to add support for `--bazelrc` to use for additional configuration.

`--config` is useful in this case, but it is only limited to `.bazelrc`.

**Comment by achew22** [comment]
It's very simple to add support for a new flag, [right here](https://github.com/bazelbuild/bazel-watcher/blob/4259108b33a9318ba5d0b3edede162edf9f71fc8/ibazel/main.go#L27). Would you be willing to send in a PR to support this flag, and any others you can think of?

**Comment by libsamek** [comment]
Yeah, I would. So I understand you correctly I just need to add it to `overrideableBazelFlags`?

**Comment by achew22** [comment]
Yeah, that's exactly what you would need to do. Feel free to add any other flags you are interested in having through ibazel

**Comment by libsamek** [comment]
This is resolved with #13316.
