### ISSUE TITLE
Call hotswap when ibazel run'ing Java binaries

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-watcher#28]
I don't run any Java binaries so this is a FR for someone who does. It would be possible to detect that you're running a java_binary under the hood and leave the command running in the background then hot swap in the newest version of the code to prevent having to restart the server.

**Comment by sgammon** [comment]
hi @achew22, thank you for suggesting this, i am from the future, and i am the user who needs this FR. lol

is this something that i can potentially contribute?

**Comment by achew22** [comment]
@sgammon this would be a great thing to contribute! We even have a nice hook for you.

What you're going to need to do is create a new [`Command`](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/command/command.go#L35) that calls the appropriate command for hotswapping the Java binary out. You'll do that in the `NotifyOfChanges` function. Feel free to put the code in the same directory as [`notify_changes.go`](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/command/notify_command.go#L91), and even use it as a template for writing this.

I'll think about how an e2e test can be written for this so that we can validate the behavior doesn't regress.

**Comment by sgammon** [comment]
if we can keep this open, i'd love to pick it up over a weekend in the next month or so

**Comment by achew22** [comment]
Sounds good to me!

**Comment by sgammon** [comment]
lol @achew22

**Comment by achew22** [comment]
Such an aggressive robot!
