### ISSUE TITLE
error setting higher file descriptor limit for this process: invalid argument

### ISSUE THREAD

**Issue by bugzpodder** [bazelbuild/bazel-watcher#285]
getting:
`error setting higher file descriptor limit for this process: invalid argument`
when running ibazel.

Have to run ulimit -n 10000 manually.

macosx

**Comment by achew22** [comment]
@bugzpodder could you tell me the OS, OS version and iBazel version you're running?

**Comment by bugzpodder** [comment]
iBazel - Version v0.10.2
macos mojave 10.14.6
go 1.12.1
Seem to be related to https://github.com/golang/go/issues/30401
