### ISSUE TITLE
Make it possible to not restart the server and only rebuild the data dependencies of a job (while leaving it running)

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-watcher#29]
To quote @mprobst,

> I found that to be more useful than respawning the binary. In
particular for servers that often take a long time to start, it's useful to
rebuild their assets (think: JS, TypeScript, etc) without restarting the
server.

**Comment by alexeagle** [comment]
Definitely need this for Karma, it takes a while for karma to start up, launch its server, launch and connect to a browser.

**Comment by achew22** [comment]
@alexeagle Do you know if this is done with a bazel query (seems likely to be slow) or by parsing the BUILD file directly or is there another mechanism that I'm unaware of

**Comment by alexeagle** [comment]
I think you are already watching all the right files? You just shouldn't
kill the program, instead run another bazel build behind the running
program.
If we get lost, we'll probably need Martin for details.

**Comment by achew22** [comment]
100% agree on that, but how do you detect if the target has the tag "no_seriously_dont_kill_me". The only idea I have off hand is to do `bazel query attr(tags, no_seriously_dont_kill_me, //path/to:target)` and see if the target is returned. Do you have any other ideas on that?

**Comment by alexeagle** [comment]
Can we always leave binaries running under `ibazel run`? I don't think iblaze has a feature to restart the binary on changes?

**Comment by achew22** [comment]
@mrmeku  and I worked on this Friday night (https://github.com/mrmeku/bazel-watcher/commit/54930bf425faf4c35a485c5ae36357fe8eaa7910) by refactoring the way commands are launched. We got pretty far and think we have a plan for handling the numerous edge cases. @mrmeku is going to fix up the tests and send me a PR which I'll merge then it'll be pretty simple to add the support for not restarting the binary on change

**Comment by alexeagle** [comment]
sweet, I'd be excited to have this for AngularMix, my demo will be a lot
faster if karma stays running

**Comment by mrmeku** [comment]
@achew22 I think this can be closed now can't it?

**Comment by achew22** [comment]
I want to close it when it's documented and e2e tested. It's not done till it's documented :wink:

**Comment by achew22** [comment]
I think this is reasonably well e2e tested now. Closing.
