### ISSUE TITLE
Bash trap works with bazel but not with ibazel

### ISSUE THREAD

**Issue by kevinsimper** [bazelbuild/bazel-watcher#291]
When I run this with bazel, I can catch the SIGINT, but when i run it with ibazel, the script does not catch it, how can that be?

Is there an example of where it works? :)

```
#!/bin/sh
trap cleanup "SIGINT"

cleanup()
{
  echo 'Caught Signal'
}

bash myprocess.sh
```

**Comment by achew22** [comment]
What else have you tried and looked up? Do you have any theories why it isn't working the way you expect? Maybe we can figure this out together.

**Comment by kevinsimper** [comment]
@achew22 Thanks for responding, I made a minimal example https://github.com/kevinsimper/bazel-watch-example

Here you can see the logs and no date was written to the logfile:
```
$ bazel run //:run
INFO: Analyzed target //:run (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:run up-to-date:
  bazel-bin/run_final.sh
INFO: Elapsed time: 0.154s, Critical Path: 0.04s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
Running
^CCaught Signal
```
```
$ ibazel run //:run
error setting higher file descriptor limit for this process: invalid argumentQuerying for files to watch...
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
Runing //:run
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
Loading:
Loading: 0 packages loaded
Analyzing: target //:run (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:run (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:run up-to-date:
  bazel-bin/run_final.sh
INFO: Elapsed time: 0.119s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Starting...
Running
^C
Subprocess killed from getting SIGINT (trigger SIGINT again to stop ibazel)
```

```
$ bazel version
Build label: 0.29.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 10 13:47:42 2019 (1568123262)
Build timestamp: 1568123262
Build timestamp as int: 1568123262
$ ibazel version
iBazel - Version v0.10.2
```

**Comment by kevinsimper** [comment]
It looks to be sending SIGKILL which can't be trapped 

https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/command/default_command.go#L55

That seems like a inconsistency with how bazel works?

**Comment by achew22** [comment]
I think we should do a bit more unpacking. I think, possibly in addition to an ibazel issue, there is an issue with your script. Your [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) is set to `/bin/sh` and I don't think you can pass in the named trap to `sh`. It appears you can set the trap that way in `bash`, but not in `sh`.

Sample output:

```
achew22@lappy:/tmp$ ./test1.sh
trap: SIGINT: bad trap
Running
^C
achew22@lappy:/tmp$ cat log.txt
cat: log.txt: No such file or directory
achew22@lappy:/tmp$ cat ./test1.sh
#! /bin/sh
trap cleanup "SIGINT"

cleanup()
{
  echo 'Caught Signal'
  echo $(date) >> log.txt
  exit 0
}

echo "Running"
cat
```

Notice that doesn't work. But changing the shebang to `/bin/bash`, it seems to work:

```
achew22@lappy:/tmp$ ./test1.sh 
Running
^CCaught Signal
achew22@lappy:/tmp$ cat log.txt
Mon Oct 7 21:50:10 MDT 2019
achew22@lappy:/tmp$ cat test1.sh
#! /bin/bash
trap cleanup "SIGINT"

cleanup()
{
  echo 'Caught Signal'
  echo $(date) >> log.txt
  exit 0
}

echo "Running"
cat
```

What happens with that slight tweak?

**Comment by kevinsimper** [comment]
@achew22 Did you try the example? 😄https://github.com/kevinsimper/bazel-watch-example

I updated it, it still works with bazel and not with ibazel

**Comment by kevinsimper** [comment]
And I used sh, because that is the terminal available in alpine, and it works there 😄

```
$ docker run -it alpine sh
/ # apk add nano
/ # nano run.sh
/ # cat run.sh
#!/bin/sh
catch_signal () {
  echo "Ctrl+C signal catched"
  echo "Exiting"
  exit 0
}

trap 'catch_signal' SIGINT

while true; do
  sleep 1
done

/ # chmod +x run.sh
/ # ./run.sh
^CCtrl+C signal catched
Exiting
```

**Comment by mrmeku** [comment]
@achew22 Here's the integration test bazel uses to test its process kill logic: https://github.com/bazelbuild/bazel/blob/7454417833dc240f6ba359ecb2539f19d8da625d/src/test/shell/integration/process-wrapper_test.sh#L87

@kevinsimper is right that ibazel has a divergence from Bazel's logic. Bazel sends SIGTERM first and only sends SIGKILL after a timeout if the process doesn't die.

**Comment by kevinsimper** [comment]
@mrmeku Thanks for looking at it 👍

**Comment by achew22** [comment]
@mrmeku, since you seem to have become a UNIX process signaling expert in the past 24 hours I'm going to ask you about all my process trapping questions from here on out!

@kevinsimper, would you be willing to put a test together in the e2e dir that demonstrates the issue now that we know for sure when it's fixed? As a rough sketch you could start with the [simple](https://github.com/bazelbuild/bazel-watcher/blob/master/e2e/simple/simple_test.go) one and have it write out a couple of files.

```
-- BUILD.bazel --
sh_binary(
  name = "sleep",
  srcs = ["sleep.sh"],
)
-- sleep.sh --
#! /usr/bin/env bash
catch_signal () {
  echo "Ctrl+C signal caught"
  exit 0
}
trap 'catch_signal' SIGINT
sleep 60m
```

Then in the test you can invoke ibazel and send it whatever signals you would like to test. You can start it with [`exec.CommandContext`](https://golang.org/pkg/os/exec/#CommandContext), which will return an [`exec.Cmd`](https://golang.org/pkg/os/exec/#Cmd) object which I'll refer to in the next snippet as `cmd`. You should then be able to signal to the process with something like:

```
if runtime.GOOS == "windows" {
	if err = cmd.Process.Signal(os.Kill); err != nil {
		t.Errorf("cmd.Process.Signal(os.Kill): %v", err)
	}
	// Check something reasonable for windows, but I'm not sure what that would be?
} else {
	if err = cmd.Process.Signal(os.Interrupt); err != nil {
		t.Errorf("cmd.Process.Signal(os.Interrupt): %v", err)
	}
	// Check something reasonable for linux/mac
}()
```

**Comment by achew22** [comment]
On second thought, even easier than that would be to just use the already existing [`IBazelTester`](https://godoc.org/github.com/bazelbuild/bazel-watcher/e2e#IBazelTester) abstraction, and add a new method `Interrupt` that looks just like [`Kill`](https://github.com/bazelbuild/bazel-watcher/blob/master/e2e/ibazel.go#L196) and then just call `Interrupt` in the test.

**Comment by kevinsimper** [comment]
@achew22 I made an example here https://github.com/kevinsimper/bazel-watch-example

**Comment by achew22** [comment]
The idea is to create a test that will live inside the `bazel-watcher` repo so that we can programatically test it and ensure there is no regression in the future.

**Comment by kevinsimper** [comment]
@achew22 Okay I can add it to this repo, I misunderstood that :)

**Comment by achew22** [comment]
@kevinsimper, is there anything I can do to help with getting the test in the mainline repo?

**Comment by karlhepler** [comment]
Hi @achew22 - I'm having exactly the same issue. ibazel claims to send SIGINT to the process group, but my traps aren't working. I've tried multiple different traps with posix sh and with bash. In all cases, my traps are not triggered. Does ibazel work out of a different process group or something? That's the only thing I can figure...

**Comment by karlhepler** [comment]
Wait! On a whim, I downloaded the latest version and it worked. I installed my version of `ibazel` with Homebrew and it looks like Homebrew's version is stuck at `0.13.1`. How does this get updated? Is this something you're able to do? Or do you think I should forgo Homebrew?

**Comment by achew22** [comment]
I do not maintain the ibazel homebrew package. That said, I can't imagine it would be hard to update. Do you know where brew is pulling the installation instructions from?

**Comment by karlhepler** [comment]
All I really know are the commands I run to get it. I'm not sure how it works other than that. I'm not sure how to trace down where it's coming from.

```
brew tap bazelbuild/tap
brew install bazelbuild/tap/ibazel
```

**Comment by karlhepler** [comment]
Maybe here? Just a guess... https://github.com/bazelbuild/homebrew-tap/blob/master/Formula/ibazel.rb

**Comment by karlhepler** [comment]
Confirmed... and it looks like someone already submitted a PR... in November. :-/

**Comment by karlhepler** [comment]
https://github.com/bazelbuild/homebrew-tap/pull/103

**Comment by karlhepler** [comment]
@achew22 - according to [CODEOWNERS](https://github.com/bazelbuild/homebrew-tap/blob/master/CODEOWNERS#L5), it looks like you might be able to merge it so it can be released?

**Comment by achew22** [comment]
Heh, looks like ibazel is the only project actually served out of there. https://github.com/bazelbuild/homebrew-tap/tree/master/Formula

Would you be interested in moving [`ibazel.rb`](https://github.com/bazelbuild/homebrew-tap/blob/master/Formula/ibazel.rb) into [homebriew-core](https://github.com/Homebrew/homebrew-core/tree/master/Formula)? I think that would allow the separate tap repo to be deleted and give a straight forward path for upgrading in the future. Should be a relatively simple PR to send

**Comment by karlhepler** [comment]
I think that would be a great thing to do after [this PR](https://github.com/bazelbuild/homebrew-tap/pull/103) is merged. I'd like to see if we can put out the "fire" before introducing a new feature.

**Comment by achew22** [comment]
While I am in the CODEOWNERS file, I'm not a repo member. This means I have no ability to merge or modify that commit. If you think you can draw the attention of someone in that repo who can commit that seems like a reasonable step forward, but I don't have a green merge button.

**Comment by karlhepler** [comment]
Gotcha. Thanks. I wasn't aware that you could not merge it. I'll see what I can do when I have a chance.
