### ISSUE TITLE
ibazel doesn't watch changes in .bzl files that affect the build

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#3]
I have a .bzl file that defines a rule, then ibazel build the rule. That .bzl file isn't watched for changes.

**Comment by achew22** [comment]
@alexeagle, this is very definitely a KI. As I see it there are two first order approximations of this problem.

1.  We could watch all BUILD files that are in packages that are tracked and scan them for load statements.
2.  We could watch for changes on any bzl file nested inside the current WORKSPACE and retrigger a build of all targets when that happens.

The latter is almost certainly easier to implement but if you have thoughts on the matter I would be very interested to hear them.

**Comment by alexeagle** [comment]
I guess the bazel query doesn't tell us about these files? @mprobst to the rescue

**Comment by mprobst** [comment]
It does, like this:

```
let d = deps(set(targetA target B ...) in
buildfiles($d) + separator + kind("source file", $d)"
```

The separator is a trick to avoid running two `bazel query` commands, which might improve performance a bit, though I never measured that in a principled way. One command is also atomic, which might be nice. In any case, this gives you first the list of all `BUILD` and `.bzl` dependencies, then the separator, then the list of all source files.

**Comment by achew22** [comment]
With the separator it appears to be expecting a target. In Google I presume you can just pick a fixed target that has no dependencies and has private visibility (thus preventing the problem where the dependencies of the target you're ibazel building contains the sentinel value) but there is no guarantee that any target in particular will be there in Bazel. I could probably pull out of `@bazel_tools//...` but I don't know how stable that set is.

Mostly recording my thoughts here. If someone has a clever trick here I'm interested

**Comment by mprobst** [comment]
Agreed. I think it will be fine to just do two queries, this might be a
case of premature optimization anyway.

**Comment by achew22** [comment]
@mprobst poked this a bit more and I'm starting to feel happy with how it works. You mentioned racy behavior which I wasn't able to replicate with things as they stand now. Do you have any tips on situations where this seems to fail?

**Comment by mprobst** [comment]
@achew22 well, in theory the user could change the BUILD structure in between your two blaze query operations. But I think that doesn't matter in practice.

**Comment by alexeagle** [comment]
Thanks!
