### ISSUE TITLE
Request: add CLI option to set debounce delay value

### ISSUE THREAD

**Issue by martijnthe** [bazelbuild/bazel-watcher#31]
It would be nice to set the debounce delay value through a CLI option.
100ms is hard-coded today, but some set ups may require longer values.

**Comment by achew22** [comment]
Can you help me understand the circumstances where a 100ms debounce isn't long enough?

**Comment by alexeagle** [comment]
I also found myself decreasing the debounce while benchmarking angular devserver round-trip time, where I have 2000ms budget to work with, the variance of up to 99ms in watch delay can matter.

**Comment by martijnthe** [comment]
> Can you help me understand the circumstances where a 100ms debounce isn't long enough?

In my set up, multiple source files are synced over the network in a batch.
100ms usually just a bit too short to avoid triggering bazel multiple times.

And as @alexeagle shorter times may also be desirable in other set ups...

**Comment by martijnthe** [comment]
Thanks for the 🎁 !
