### ISSUE TITLE
ibazel run not forwarding ctrl-c to processes

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel-watcher#32]
I have a server I use `ibazel run` on that uses Go's `Server.Shutdown` on syscall.SIGTERM and os.Interrupt on mac OS 10.12.6. Sometimes, ibazel seems to leak a process out the side, causing the server on the next reboot to fail because the port is already claimed by that leaked process.

Haven't dug into the code yet to figure out the deal, but dealt and fixed with similar issues in http://github.com/jmhodges/justrun. (The fix, without looking at ibazel's code, might be some stuff like https://github.com/jmhodges/justrun/blob/master/cmdwrap.go#L23-L25 and https://github.com/jmhodges/justrun/blob/master/cmdwrap.go#L41-L46 to work probably)

**Comment by jmhodges** [comment]
Oh, lol, that code is in there. So, the bug is elsewhere!

**Comment by jmhodges** [comment]
Oh this might just be as simple as a `i.cmd.Wait()` added in the next line after `syscall.Kill(-i.cmd.Process.Pid, syscall.SIGKILL)`. I'm going to run with that patch in place.

**Comment by jmhodges** [comment]
Oh oh I figured it out. ibazel isn't propagating my Ctrl-C (SIGTERM)'s I'm sending to it  the server process.

That cmd.Wait is still required to avoid collisions because Kill isn't an atomic operation, too.

**Comment by jmhodges** [comment]
(To handle the SIGTERM propagatin case in justrun, I had to write https://github.com/jmhodges/justrun/blob/master/justrun.go#L121-L128 and https://github.com/jmhodges/justrun/blob/master/cmdwrap.go#L64-L67)

**Comment by achew22** [comment]
Fixed by #35
