### ISSUE TITLE
parallel run support

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/bazel-watcher#320]
It's common to run multiple targets at the same time, right now you have to use some utility to do this. We use the `concurrently` npm module to do this: `concurrently "npx ibazel run :server1" "npx ibazel run :server1"`. 
While this works I believe it could be more effcient and easier for end users if `ibazel` could support this use case.
For example: `npx ibazel run :server1 :server2`

**Comment by achew22** [comment]
It is also possible to write a build target that invokes both of your binary targets. This has the added benefit of allowing you to do this like port mapping between the jobs. I have a crappy 3 line bash script that does this in my repo. Have you tried something like that out?

**Comment by Toxicable** [comment]
Ah yeah, I just came accross https://github.com/atlassian/bazel-tools/tree/master/multirun
Looks like a better solution than doing it in `ibazel` since you can express the dep between bins in skylark.

Closing this since I think using multirun is the "proper" way todo it

**Comment by flolude** [comment]
Multirun seems great, but it doesn't watch for code changes. Or is there some way to automatically restart the target which changed?

**Comment by achew22** [comment]
What does it to now? Does it just launch the multirun target and then hang? I would expect it to relaunch every binary on any file change. What is actually happening?

**Comment by Toxicable** [comment]
@flolude if you use `ibazel` with it then ibazel will watch for changes.
@achew22 it will launch all your targets in parallel (if you set paralle = True) then when any file changes they all restart if you're using ibazel

**Comment by flolude** [comment]
My fault. It works fine :)

**Comment by flolude** [comment]
Is `multirun` suitable for a large project with many microservices running in parallel or would you rather use something like `docker-compose` for it?

**Comment by joprice** [comment]
I'm having issues with multirun when not all of the targets support `ibazel_notify_changes`   https://github.com/atlassian/bazel-tools/issues/87. The processes that don't support it never get restarted. I don't understand how the tags are propogated fully, so I'm not sure if I need to add support for ibazel to each target, or if there's some other way to exlude them.
