### ISSUE TITLE
$TEST_TMPDIR is deleted across reloads

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/bazel-watcher#323]
It appears that the directory $TEST_TMPDIR is cleared upon subsequent runs; only the first run has a $TEST_TMPDIR path that exists on disk. It would be helpful to have a directory that would exist across runs. 

Is there a proper way to maintain a tmp dir for the duration of an ibazel process?

**Comment by achew22** [comment]
Could you try running two `bazel test`s back to back (with a small change to your files) and tell me if this issue happens?

**Comment by joeljeske** [comment]
Yes, Bazel clears this upon completion of a test. Subsequent runs are given a new $TEST_TMPDIR each time. 

With iBazel, there are 2 issues:
- I only ever have access to the first temp dir, subsequent runs have a new temp dir but I cannot access the new variable. 
- I am not given a temp dir that lasts for the duration of iBazel across runs. 

 My particular request is for needs the second use case, however the first could also be a valid use case. I’m honestly not sure which case should be used for $TEST_TMPDIR and which case should be a new variable that only exists for iBazel.

**Comment by achew22** [comment]
@joeljeske, the best way to think of iBazel is as a program that runs `bazel test` on your behalf over and over again (that's how it is actually implemented). If that doesn't work in unwrapped Bazel, it's unlikely we can make it work in iBazel. Could you elaborate a bit on what the output from the first run that you would like to make available in the 2nd run, as well as some general information about what you're using (What rule set you're using, the output of `bazel version`, etc.) and what the 40000 ft. objective of this is?

Also as a side note, sharing anything between test runs is going to preclude your ability to get cache hits on runs, or use remote build execution to distribute the work in a cluster. 

Thanks!
