### ISSUE TITLE
Stop running subprocesses as soon as changes are detected

### ISSUE THREAD

**Issue by borkaehw** [bazelbuild/bazel-watcher#333]
Not sure if it's a bug or a design in mind.

We use iBazel to run a tcp server. When we make a change, iBazel behaves like
1. detect changes
2. build new code
3. stop old server
4. start new server

This is not ideal for us. Building new code could take few minutes. Developers can still hit the old server, which could be confusing sometimes to see things are not changing. The only way to tell is by looking at the console. It would be ideal if iBazel can stop the server right away the changes have been detected.

We tried to identify how iBazel starts and stops subprocesses but no luck. we really help some helps. Thanks.

**Comment by achew22** [comment]
There is a fine line between bug and feature. I use this feature regularly in my testing where I want to see the results of the current test finish, then as soon as the test finishes restart the compile/test loop.

That said, I don't think there is any reason we can't tag binaries with something like `IBAZEL_SHORT_CIRCUIT_RESTART` or something like that. Would you be interested in having that functionality?

**Comment by borkaehw** [comment]
That would be great. It sounds like what we are expecting. How complex would it be to implement it?

**Comment by achew22** [comment]
If you wanted to modify the code here to introduce a new switch for short circuiting, that would be a good place for it. I don't think it would be extremely difficult, the hardest part would probably be writing an e2e test for the case where that tag isn't applied.

https://github.com/bazelbuild/bazel-watcher/blob/e695e93213e803ca4091f39ef121fbddb2d39c42/ibazel/ibazel.go#L389

**Comment by mrmeku** [comment]
@achew22 I think that this might be a sane default for binaries tagged with `ibazel_live_reload`

What do you think?

**Comment by achew22** [comment]
I'm not sure this is a good default for `ibazel_live_reload`. The major use for live reload is when you're trying to rapidly iterate on your frontend. If the frontend is going to reload every time then you've got to persist the dev server state because the server will lose it every time it comes up. It also means if you're doing a Java server or something with long start up times then you're going to have to wait 30s on every file change to see results.

Maybe I'm missing something, can you help me understand the idea better?

**Comment by mrmeku** [comment]
Assume that a typical javascript rebundling cycle takes ~8 seconds

A common pattern I find myself in is fixing a small error, saving, realizing a made a small syntax error, re-saving and then having to wait 16 seconds to see if my code compiles

My use case of devservers usually do not involve listening for the ibazel messages themselves. Rather, after a JS recompilation the browser just reloads itself. So I just try to optimize for getting a successful build as quickly as possible. Intermediate results don't matter to me

**Comment by achew22** [comment]
Ah, this seems like it'll be useful then. Thanks for sending in the PR!
