### ISSUE TITLE
Try resolve bazel binary from @bazel/bazelisk installed locally

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/bazel-watcher#339]
Now that @bazel/bazelisk is deployed to npm https://www.npmjs.com/package/@bazel/bazelisk
We should try resolve the bazel binary from that local install.

**Comment by achew22** [comment]
The file in question is [here](https://github.com/bazelbuild/bazel-watcher/blob/master/release/npm/index.js). The way I would go about developing it would be to `npm install @bazel/ibazel` and `@bazel/bazelisk` and then manually edit the `index.js` that is in the `ibazel` until it exhibits all the functionality you need. Then copy your changed `index.js` over into this repo and send a PR.

Is there anything else you need from me to get this done?

**Comment by alexeagle** [comment]
Last time I made a related change, we did it in the go code:
https://github.com/bazelbuild/bazel-watcher/pull/275/files

I don't remember enough context to say which is better or more correct though

**Comment by alan-agius4** [comment]
This is pretty similar to https://github.com/bazelbuild/bazel-watcher/issues/341 seems like the changes in https://github.com/bazelbuild/bazel-watcher/pull/275 have regressed.
