### ISSUE TITLE
ibazel can't locate bazel if not in $PATH

### ISSUE THREAD

**Issue by alan-agius4** [bazelbuild/bazel-watcher#341]
Followup from https://github.com/bazelbuild/bazel-watcher/issues/252

**Reproduction:** 
```
npx @angular/cli@next new bazel-angular
cd bazel-angular
ng add @angular/bazel@next
npm i @bazel/ibazel@latest --save-dev // ensure using the updated ibazel version since it's outdate in the schematics
ng serve
```

```
ng serve
iBazel [8:26AM]: Error getting Bazel info exec: "bazel": executable file not found in %PATH%
iBazel [8:26AM]: Querying for files to watch...
iBazel [8:26AM]: Bazel query failed: exec: "bazel": executable file not found in %PATH%
iBazel [8:26AM]: Bazel query failed: exec: "bazel": executable file not found in %PATH%
iBazel [8:26AM]: Running //src:devserver
iBazel [8:26AM]: Error running Bazel exec: "bazel": executable file not found in %PATH%
c:\...\node_modules\@bazel\ibazel\bin\windows_amd64\ibazel.exe failed with code 4.
```

**Versions:** 
```
OS: Windows
@bazel/bazel: 2.0.0,
@bazel/ibazel: 0.11.1
```

**Workaround:**
```
npm i -g @bazel/bazel
```

**Comment by alan-agius4** [comment]
Note: this also happens on Linux

```
iBazel [12:21PM]: Error getting Bazel info exec: "bazel": executable file not found in $PATH
iBazel [12:21PM]: Querying for files to watch...
iBazel [12:21PM]: Bazel query failed: exec: "bazel": executable file not found in $PATH
iBazel [12:21PM]: Bazel query failed: exec: "bazel": executable file not found in $PATH
iBazel [12:21PM]: Running //src:devserver
iBazel [12:21PM]: Error running Bazel exec: "bazel": executable file not found in $PATH
/workspace/rules_nodejs/examples/angular/node_modules/@bazel/ibazel/bin/linux_amd64/ibazel failed with code 4.
```

**Comment by achew22** [comment]
I think this should be fixed in the latest release. Can you verify that?

**Comment by alan-agius4** [comment]
@achew22 I just checked but it seems that the original issue is solved. However with (v0.12.3) now it seems that it's trying to load the `bazelisk` binary, but I am not not using `bazelisk`, I am using the standard `bazel` binary.

```
iBazel [8:17AM]: Error getting Bazel info exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
iBazel [8:17AM]: Querying for files to watch...
iBazel [8:17AM]: Bazel query failed: exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
iBazel [8:17AM]: Bazel query failed: exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
iBazel [8:17AM]: Running //src:devserver
iBazel [8:17AM]: Error running Bazel exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
C:\git\cli-repos\bazel-angular\node_modules\@bazel\ibazel\bin\windows_amd64\ibazel.exe failed with code 4.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by afifalfiano** [comment]
> @achew22 I just checked but it seems that the original issue is solved. However with (v0.12.3) now it seems that it's trying to load the `bazelisk` binary, but I am not not using `bazelisk`, I am using the standard `bazel` binary.
> 
> ```
> iBazel [8:17AM]: Error getting Bazel info exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
> iBazel [8:17AM]: Querying for files to watch...
> iBazel [8:17AM]: Bazel query failed: exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
> iBazel [8:17AM]: Bazel query failed: exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
> iBazel [8:17AM]: Running //src:devserver
> iBazel [8:17AM]: Error running Bazel exec: "C:\\git\\cli-repos\\bazel-angular\\node_modules\\@bazel\\bazelisk\\bazelisk-windows_amd64.exe": file does not exist
> C:\git\cli-repos\bazel-angular\node_modules\@bazel\ibazel\bin\windows_amd64\ibazel.exe failed with code 4.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

i have the same issue, any solution here?

**Comment by achew22** [comment]
I think the `bazelisk` thing has also been fixed. Closing but please reopen if there are any more issues.

**Comment by afifalfiano** [comment]
> I think the `bazelisk` thing has also been fixed. Closing but please reopen if there are any more issues.

okee , this problem was solved, cause the bazelisk was deprecated from bazel, Thanks
