### ISSUE TITLE
Querying for files to watch... )) was unexpected at this time. Bazel query failed: exit status 255

### ISSUE THREAD

**Issue by alan-agius4** [bazelbuild/bazel-watcher#342]
**Reproduction:** 
```
npx @angular/cli@next new bazel-angular
cd bazel-angular
ng add @angular/bazel@next
npm i @bazel/ibazel@latest --save-dev // ensure using the updated ibazel version since it's outdate in the schematics
ng serve
```

```
ng serve
iBazel [9:00AM]: Querying for files to watch...
)) was unexpected at this time.
iBazel [9:00AM]: Bazel query failed: exit status 255
Loading: 0 packages loaded
Loading: 109 packages loaded
    currently loading: @nodejs_windows_amd64// ... (3 packages)
Loading: 218 packages loaded

Loading: 218 packages loaded
iBazel [9:00AM]: Running //src:devserver
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
iBazel [9:00AM]: Launching with notifications
listening on :35729
```

**Versions:** 
```
OS: Windows
@bazel/bazel: 2.0.0,
@bazel/ibazel: 0.11.1
```

**Workaround:**
```
npm i -g @bazel/bazel
```

**Comment by achew22** [comment]
To me this looks like an issue with the angular cli. If there is something specific iBazel needs to do, please reopen.

**Comment by alan-agius4** [comment]
I don’t think this is a cli issue. The cli command just spawns the `ibazel` with a target.

**Comment by alan-agius4** [comment]
That said, I’ll take another look at this in the coming days.

**Comment by simeyla** [comment]
> To me this looks like an issue with the angular cli. If there is something specific iBazel needs to do, please reopen.

@achew22  if bazel knows the filename it would be helpful to say where

**Comment by simeyla** [comment]
This is a nightmare! I finally figured out I can add a `.bazelrc` file with the following:

    startup --output_user_root=bazel_stuff,--verbose_failures

This contained the very revealing error that:

> WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.14.1/node-v12.14.1-win-x64.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

Sure enough - that file does not actually exist.

So I updated node myself and now I get something like this:

```
npm ERR! ng-bazel3@0.0.0 postinstall: `ngcc --properties es2015 browser module main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-bazel3@0.0.0 postinstall script.
```
