### ISSUE TITLE
[Windows] - Querying for files to watch... )) was unexpected at this time. Bazel query failed: exit status 255

### ISSUE THREAD

**Issue by alan-agius4** [bazelbuild/bazel-watcher#344]
Follow up on https://github.com/bazelbuild/bazel-watcher/issues/342 as I managed to replicate it in anothe repo.

**Reproduction:**
```cmd
git clone git@github.com:bazelbuild/rules_nodejs.git
cd rules_nodejs/examples/angular
yarn
yarn ibazel run //src:devserver
```

Error
```
yarn ibazel run //src:devserver
yarn run v1.19.1
$ C:\git\rules_nodejs\examples\angular\node_modules\.bin\ibazel run //src:devserver
iBazel [8:17AM]: Querying for files to watch...
)) was unexpected at this time.
iBazel [8:17AM]: Bazel query failed: exit status 255
Loading: 0 packages loaded
Loading: 93 packages loaded
    currently loading: @nodejs_windows_amd64// ... (4 packages)
Loading: 301 packages loaded

Loading: 301 packages loaded
iBazel [8:17AM]: Running //src:devserver
Loading: 0 packages loaded
Loading: 0 packages loaded
```

Versions:
```
OS: Windows
@bazel/bazel: 2.0.0,
@bazel/ibazel: 0.11.1
```

**Comment by achew22** [comment]
Can you build a copy of ibazel where on the first line of `main()` you print out `os.Args` before doing any flag parsing and copy that string back here? I'm unable to replicate this on a linux box and don't have a Windows machine. If it is possible to make a really small repo (< 100 lines) that I could put into an e2e test that would also work since I can use the CI system to pretend that I have a copy of windows.

Thanks!

**Comment by alan-agius4** [comment]
Hi @achew22, I tried the latest (0.12.3) ibazel with bazelisk and it seems that this issue is no longer reproducible.

I do get 2 new errors now;
```
iBazel [8:27AM]: Error reading config: open .bazel_fix_commands.json: The system cannot find the file specified.
iBazel [8:27AM]: Use default regex
iBazel [8:28AM]: Error writing build to stdin: write |1: The pipe is being closed.
``` 

I'll try to make a repo for this in the coming days.

I am going to close this issue as the original problem seems to have been solved.

**Comment by achew22** [comment]
Thanks for reviewing this. WRT the 2 errors:

1) `error reading config...` we should probably make that warn that the user doesn't have a `.bazel_fix_commands.json` file and provide an optional fix of creating that file for them.
2) I think this is an instance of https://github.com/bazelbuild/bazel-watcher/issues/300, but I would love a repro if it is different.
