### ISSUE TITLE
Support multiple tartget

### ISSUE THREAD

**Issue by jjangga0214** [bazelbuild/bazel-watcher#351]
Hi, currently `ibazel` does not support multiple targets at once.

For example,
`ibazel run //foo:bin //bar:bin`
only runs `//foo:bin`, not both.

I think it'd really convenient in such a case when we want to run multiple processes in parallel (e.g. web applications) in a local development environment.

Though there's https://github.com/atlassian/bazel-tools/tree/master/multirun, its list has to be written statically. When there are many runnable targets, declaring every possible combination, or writing temporary `multirun` rule would be somewhat cumbersome. 

So allowing multiple targets by CLI would still be helpful.

**Comment by achew22** [comment]
Unfortunately, iBazel only provides the ability to invoke `bazel` commands when their dependencies change. If you file a bug against the main Bazel and they add it in, I would be happy to add it to iBazel.

WRT the dynamism of your repo, you might find that there are fewer combinations than you anticipate. How many binaries are you really launching?

**Comment by pauldraper** [comment]
> How many binaries are you really launching?

Several API services, several background task workers, headless chrome for PDF generation, PostgreSQL database, Elaticsearch database. Depends what is being edeveloper.

The problem isn't just the variability. I've built a `multirun` rule that uses `selects()` to dynamically choose services.

But that's not a great solution; every time I change on file, every single running services restarts.

It would be far better if bazel watcher could natively handle that.

I'm looking at writing something myself.
