### ISSUE TITLE
Bazelisk regression

### ISSUE THREAD

**Issue by YvanGuidoin** [bazelbuild/bazel-watcher#352]
Hello,

Bazelisk support was working fine with 0.12.0, but both 0.12.1 and 0.12.2 are again not seeing the bazel install from bazelisk:

```
Error getting Bazel info exec: "bazel": executable file not found in $PATH
```

**Comment by achew22** [comment]
Can you try cleaning out `node_modules` and tell me if it is still happening for you. I have not been having this issue in my repo, but am interested to fix it if you're still experiencing it.

**Comment by YvanGuidoin** [comment]
Removed node_modules, cleaned yarn cache then `yarn` and same issue:
```
yarn run v1.22.0
$ ibazel run --bazelrc=config/local.bazelrc :vscenebackend.apply
iBazel [9:34AM]: Error getting Bazel info exec: "bazel": executable file not found in $PATH
iBazel [9:34AM]: Querying for files to watch...
iBazel [9:34AM]: Bazel query failed: exec: "bazel": executable file not found in $PATH
iBazel [9:34AM]: Bazel query failed: exec: "bazel": executable file not found in $PATH
iBazel [9:34AM]: Running :vscenebackend.apply
iBazel [9:34AM]: Error running Bazel exec: "bazel": executable file not found in $PATH
error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Ubuntu 19.10
yarn 1.22.0
@bazel/bazelisk 1.3.0
@bazel/ibazel 0.12.2

But if I revert @bazel/ibazel to 0.12.0 everything is fine and it finds bazelisk

**Comment by devversion** [comment]
I can confirm that `@bazel/bazelisk` is no longer being considered on my end. Updated from `0.12.0` to `0.12.2`.

**Comment by Multiply** [comment]
I am unsure if this is related, but a non-npm installed bazelisk is not used over the default bazel installation with 1.12.2 either.

**Comment by achew22** [comment]
I just released https://github.com/bazelbuild/bazel-watcher/releases/tag/v0.12.3, can you check if this works now?

**Comment by Multiply** [comment]
Works for me now.

**Comment by achew22** [comment]
Sorry for the breakage.
