### ISSUE TITLE
Use new env var to use bazel path

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/bazel-watcher#353]
It would be helpful to support a var “IBAZEL_BAZEL_PATH” that would point to the desired bazel executable. This would allow me to explicitly setup my environment to point to the proper bazel. 

The baze_path flag is less ideal as it requires me to configure it at invocation time.

**Comment by achew22** [comment]
In principle I don't oppose this change. The code would go in [here](https://github.com/bazelbuild/bazel-watcher/blob/d195868dcd52bac4e570f86ad19df9f5dfa13684/bazel/bazel.go#L103) and shouldn't require more than checking if that environment variable is set (see [this](https://gobyexample.com/environment-variables) for more docs on how to do environment variables in golang). If you could also add an `IBAZEL_BAZELISK_PATH` that would be appreciated. Also, please note that `os.Getenv` returns an empty string in the case that the value isn't set, so you'll probably do something like

```
if os.Getenv("IBAZEL_BAZEL_PATH") != "" {
  return os.Getenv("IBAZEL_BAZEL_PATH")
}
```

**Comment by joeljeske** [comment]
I would imagine that one would set IBAZEL_BAZEL_PATH to bazelisk instead of having separate variables. How would iBazel use IBAZEL_BAZELISK_PATH?

**Comment by achew22** [comment]
@joeljeske as I understand it, bazelisk is designed to have the same command line flags as Bazel. If you were to add the `IBAZEL_BAZEL_PATH` code described above [here](https://github.com/bazelbuild/bazel-watcher/blob/e695e93213e803ca4091f39ef121fbddb2d39c42/bazel/bazel.go#L97), you could just set it to be the path to your `bazelisk` binary.
