### ISSUE TITLE
ibazel not connecting to bazel server on VPN

### ISSUE THREAD

**Issue by jcroldan** [bazelbuild/bazel-watcher#356]
Hi,

i am trying to use ibazel to build my angular 9 app and watch for changes as i code, but when i use it connected to my vpn it keeps waiting forever to connect to bazel server.

When using bazel command "build **--batch** run //src" to build my app, bazel command is able to connect to the server when connected to vpn.

It could be possible to allow ibazel behave like bazel using the --batch option flag? I know it is deprecated but it is the only way i have found to getting working with vpn.

My OS is in Widnows 10.
My vpn client is Network Connect Pulse Secure 8.3.7.65025
bazel version: "@bazel/bazel": "2.1.0",
ibazel version: "@bazel/ibazel": "0.11.1",

Thank you very much.

Best regards.

**Comment by achew22** [comment]
Hey @jcroldan, thanks for submitting an issue. I'm trying to understand this a little better. Are you saying that when you invoke `ibazel`, it is unable to talk to `bazel`? Or are you saying something else?

`ibazel` doesn't invoke `bazel` over the network at all, but instead invokes it as a subcommand. Is it possible that this issue is because the `--batch` flag is required in your development environment? If so, have you tried setting `--batch` in your [`bazelrc`](https://docs.bazel.build/versions/master/guide.html#bazelrc)? That would allow you to set `--batch` on all your builds (even though it is deprecated).

**Comment by jcroldan** [comment]
Hi, @achew22, thank you very much for your reply.

This is the log from ibazel command when connected to vpn:
```
> ibazel run //src:devserver

iBazel [8:32PM]: Error getting Bazel info exit status 37
iBazel [8:32PM]: Querying for files to watch...
Killed non-responsive server process (pid=25820)
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 28 seconds ...
```
This is why i said it was trying to connect to bazel server.

After adding "build --batch" to my .bazelrc file, i still get the same error..

**Comment by achew22** [comment]
You would need to add `run --batch` to your `.bazelrc` as well for that to affect `bazel run`. Could you try that and report back here?

**Comment by jcroldan** [comment]
Added run --batch as you said but still not working:

.bazelrc
```
# Make TypeScript and Angular compilation fast, by keeping a few copies of the
# compiler running as daemons, and cache SourceFile AST's to reduce parse time.
build --strategy=TypeScriptCompile=worker
build --strategy=AngularTemplateCompile=worker

# Don't create bazel-* symlinks in the WORKSPACE directory, except `bazel-out`,
# which is mandatory.
# These require .gitignore and may scare users.
# Also, it's a workaround for https://github.com/bazelbuild/rules_typescript/issues/12
# which affects the common case of having `tsconfig.json` in the WORKSPACE directory.
#
# Instead, the output will appear in `dist/bin`. You'll need to ignore the
# `bazel-out` directory that is created in the workspace root.
build --symlink_prefix=dist/

# Turn on --incompatible_strict_action_env which was on by default
# in Bazel 0.21.0 but turned off again in 0.22.0. Follow
# https://github.com/bazelbuild/bazel/issues/7026 for more details.
# This flag is needed to so that the bazel cache is not invalidated
# when running bazel via `yarn bazel`.
# See https://github.com/angular/angular/issues/27514.
build --incompatible_strict_action_env
run --incompatible_strict_action_env
test --incompatible_strict_action_env

build --incompatible_bzl_disallow_load_after_statement=false

test --test_output=errors

# Use the Angular Ivy compiler
# See https://github.com/angular/angular/blob/master/docs/BAZEL.md#various-flags-used-for-tests
build --define=angular_ivy_enabled=True

# Temporary define while angular depends on the legacy rollup_bundle rule.
# TODO: remove this setting after https://github.com/angular/angular/pull/33201 lands.
build --define=enable_legacy_rollup_rule=1

# Turn on managed directories feature in Bazel
# This allows us to avoid installing a second copy of node_modules
common --experimental_allow_incremental_repository_updates

build --verbose_failures --sandbox_debug --test_output=errors --spawn_strategy=standalone --genrule_strategy=standalone

build --batch

run --batch

```

```
C:\Users\jcroldan\development\gitcorp\bazel-app>npm run serve

> bazel-app@0.0.0 serve C:\Users\jcroldan\development\gitcorp\bazel-app
> ibazel run //src:devserver

iBazel [5:05PM]: Error getting Bazel info exit status 37
iBazel [5:05PM]: Querying for files to watch...
Killed non-responsive server process (pid=6484)
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 27 seconds ...
... still trying to connect to local Bazel server after 47 seconds ...
... still trying to connect to local Bazel server after 67 seconds ...
... still trying to connect to local Bazel server after 87 seconds ...
... still trying to connect to local Bazel server after 107 seconds ...
FATAL: couldn't connect to server (8480) after 120 seconds.
iBazel [5:08PM]: Bazel query failed: exit status 37
Killed non-responsive server process (pid=8480)
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 26 seconds ...
... still trying to connect to local Bazel server after 46 seconds ...
... still trying to connect to local Bazel server after 66 seconds ...
... still trying to connect to local Bazel server after 86 seconds ...
... still trying to connect to local Bazel server after 106 seconds ...
FATAL: couldn't connect to server (11660) after 120 seconds.
iBazel [5:10PM]: Bazel query failed: exit status 37
iBazel [5:10PM]: Running //src:devserver
Killed non-responsive server process (pid=11660)
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 25 seconds ...
... still trying to connect to local Bazel server after 45 seconds ...
... still trying to connect to local Bazel server after 65 seconds ...
... still trying to connect to local Bazel server after 85 seconds ...
... still trying to connect to local Bazel server after 105 seconds ...
FATAL: couldn't connect to server (10328) after 120 seconds.
iBazel [5:13PM]: Error running Bazel exit status 37
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! bazel-app@0.0.0 serve: `ibazel run //src:devserver`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the bazel-app@0.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jcroldan\AppData\Roaming\npm-cache\_logs\2020-03-06T16_13_21_822Z-debug.log
```

**Comment by achew22** [comment]
@jcroldan, hurm.... that's unfortunate. There is no place in ibazel where we log error messages that don't have the prefix of `iBazel [$TIME]:`. The errors you're seeing are most definitely from `bazel` and not from `ibazel`, which is wrapping `bazel` in subcommands. There are no network connections created to control `bazel` by `ibazel` so I hate to say it but I think the princess is in another castle.

Can you provide me with any steps that allow me to reproduce this on a machine of my own? It seems that this is a poorly configured VPN that disallows connections on the loopback which is going to be problematic in the near future when you want to visit your devserver. Have you considered a chat with your IT team to figure out if there are any configuration changes that can be made to the VPN?

**Comment by jcroldan** [comment]
@achw22, I have found this issue at Bazel repository: https://github.com/bazelbuild/bazel/issues/3602
There you can find how to reproduce the problrem.

**Comment by achew22** [comment]
From the linked issue:

> I know this is a Pulse Secure issue because it prevents bazel client from connecting to server

It sounds to me like this is an issue with the pulse secure VPN client. Please feel free to reference this issue in a ticket to them, but since I do not work for Pulse Secure I do not have the resources/spare time to run down this issue. Best of luck. If you find any other issues with `ibazel` please open an issue.

Thanks!

**Comment by jcroldan** [comment]
Ok, thank you very much.
