### ISSUE TITLE
Reads .bazel_fix_commands.json from current directory

### ISSUE THREAD

**Issue by deadmoose** [bazelbuild/bazel-watcher#373]
`--run_output` is documented as:
> Search for commands in Bazel output that match a regex and execute them, the default path of file should be in the workspace root .bazel_fix_commands.json

Calling that "the default path" is a bit of a misnomer since it's hardcoded, and then it just directly `os.Open`s that, so it looks in whatever your working dir happens to be.

**Comment by achew22** [comment]
@deadmoose yep, you're 100% right on this. I also think it's a bug. It should prepend the workspace

Useful links:
* [Place to prepend the workspace root](https://github.com/bazelbuild/bazel-watcher/blob/a34b1345ac8c090de26c979c2bff22e823c3e442/ibazel/output_runner/output_runner.go#L99)
* [Place where we find the workspace root](https://github.com/bazelbuild/bazel-watcher/blob/a34b1345ac8c090de26c979c2bff22e823c3e442/ibazel/output_runner/output_runner.go#L175)

This looks like a fairly simple simple fix to:

1. Update [`New`](https://github.com/bazelbuild/bazel-watcher/blob/a34b1345ac8c090de26c979c2bff22e823c3e442/ibazel/output_runner/output_runner.go#L56) to set a new field on the `OutputRunner` struct, `wf `[`workspace_finder.WorkspaceFinder`](https://godoc.org/github.com/bazelbuild/bazel-watcher/ibazel/workspace_finder#WorkspaceFinder) to a freshly constructed [`workspace_finder.MainWorkspaceFinder`](https://godoc.org/github.com/bazelbuild/bazel-watcher/ibazel/workspace_finder#MainWorkspaceFinder).
2. Update [readConfigs](https://github.com/bazelbuild/bazel-watcher/blob/a34b1345ac8c090de26c979c2bff22e823c3e442/ibazel/output_runner/output_runner.go#L99) to take a `workspace_finder.WorkspaceFinder` and call `FindWorkspace` on that object then [`filepath.Join`](https://golang.org/pkg/path/filepath/#Join) it with the preexisting filename in the open statement.
3. Update [the test](https://github.com/bazelbuild/bazel-watcher/blob/a34b1345ac8c090de26c979c2bff22e823c3e442/ibazel/output_runner/output_runner_test.go#L59) to pass in a [`workspace_finder.FakeWorkspaceFinder`](https://godoc.org/github.com/bazelbuild/bazel-watcher/ibazel/workspace_finder#FakeWorkspaceFinder).

Is this something you'd be interested in taking on?
