### ISSUE TITLE
nil pointer dereference when there are errors in workspace file

### ISSUE THREAD

**Issue by lewish** [bazelbuild/bazel-watcher#386]
Running ibazel from master on a project with an invalid workspace file, (for example, I had an incorrect sha on a http_archive) throws the following, and doesn't print out any useful messages from bazel itself beyond `Error getting Bazel info exit status 2`.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a2990]

goroutine 1 [running]:
main.(*IBazel).realLocalRepositoryPaths(0xc000158000, 0x921e60, 0xc000188180, 0x0)
	ibazel/ibazel_unix.go:31 +0x50
main.(*IBazel).queryForSourceFiles(0xc000158000, 0xc0001ca000, 0x27, 0x43d01f, 0xc000039000, 0x4d7c1c, 0xc0001c8014, 0xc00008d8b8)
	ibazel/ibazel.go:454 +0x6e
...
```

It would be nice if we could actually print out the verbose error from bazel itself.

**Comment by bduffany** [comment]
I'm still seeing this problem when running `USE_BAZEL_VERSION=3.5.0 ibazel run $TARGET` - ibazel version 0.13.1

**Comment by bduffany** [comment]
Nevermind, appears fixed after running `rm -rf node_modules`. Not sure why that was needed

**Comment by bduffany** [comment]
Actually, this error keeps popping up. I keep having to `rm -rf node_modules` in order to fix the problem :confused:
