### ISSUE TITLE
quiet mode

### ISSUE THREAD

**Issue by joprice** [bazelbuild/bazel-watcher#392]
Could there be a quiet mode that doesn't print the node_modules warning or the "Did you know iBazel can invoke programs..." information? Bazel output is already quite noisy.

**Comment by achew22** [comment]
This sounds like a great feature to add. The logging is already [centralized](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/log/log.go) and I would welcome a change that adds a log level flag that draws from the enum of `Log` (default), `Error`, `Fatal`

**Comment by joprice** [comment]
Sounds good. I'll put something together.
