### ISSUE TITLE
potentially misleading error message

### ISSUE THREAD

**Issue by joprice** [bazelbuild/bazel-watcher#393]
I frequently have seen the below error message and have become desensitized to it, and assume it's harmless, but have been all the while curious if it's something that shouldn't bubble up to the user:

```bash
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.147s, Critical Path: 1.83s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
iBazel [6:48PM]: Error starting process: fork/exec /var/folders/5g/4ssx2_117rv3fty7pqqv9wpc0000gp/T/bazel_script_path351664668: permission denied
```

It frequently follows errors that explain why it happened, so it makes sense in context, but the fact that it says "Not running target", but then seems to proceed to run the target is suspicious. Is this something that is better caught and swallowed?

**Comment by achew22** [comment]
Could you provide a little more context on what you're doing to invoke this? I don't see this on a regular basis. Is this a `build` or `run` what kind of target are you messing with? Is this happening exclusively in one kind of repo? What version of ibazel/bazel are you on?

**Comment by joprice** [comment]
I have a repo where I usually reproduce things. I can make a branch there and provide it here.
