### ISSUE TITLE
Error starting process: fork/exec /tmp/bazel_script_path645988457: permission denied

### ISSUE THREAD

**Issue by afifalfiano** [bazelbuild/bazel-watcher#401]
I don't know why I can't run ibazel, I already installed @ bazel / bazelisk too. A few weeks ago it could work but now it can't. Help me, please

![image](https://user-images.githubusercontent.com/47497276/83719851-28383700-a662-11ea-84fb-ca91d3a36922.png)

**Comment by afifalfiano** [comment]
> What version of `ibazel` and `bazel` are you running? Does this issue reproduce in other repositories? Are any of the ones you can reproduce it in open source? Could you make an OSS repo that demonstrates this problem?

I'm using the last version for both
![image](https://user-images.githubusercontent.com/47497276/83822867-7ef24f00-a6fc-11ea-9ec2-bc2d4fd23d58.png)

**Comment by achew22** [comment]
Unfortunately, the existence of an entry in `packages.json` has lied to me before. Could I have you invoke each of those tools the way you would normally but with the version flags for them?

There are a few more questions in that stanza, do you think you could address them as well?

Also, screenshots are great for graphical user interface bugs, but for CLI programs, it's generally nicer to just copy the text and put it in a code fence.

**Comment by afifalfiano** [comment]
Oh, sorry I haven't checked, it turns out there is version 0.13.1 and yes I have installed it but there is still an error

=====================
asus  ~/Documents/Bazel_Research/angular9   staging ●✚  ibazel run src:devserver
iBazel [9:07AM]: Error getting Bazel info exit status 2
iBazel [9:07AM]: Querying for files to watch...
iBazel [9:07AM]: Error getting Bazel info exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a2a00]

goroutine 1 [running]:
main.(*IBazel).realLocalRepositoryPaths(0xc0000ee000, 0x921e00, 0xc0000a86c0, 0x0)
ibazel/ibazel_unix.go:31 +0x50
main.(*IBazel).queryForSourceFiles(0xc0000ee000, 0xc000102030, 0x24, 0x43d01f, 0xc000036800, 0x4d7c1c, 0xc00013c014, 0x7ffd2a9df0b9)
ibazel/ibazel.go:454 +0x6e
main.(*IBazel).watchFiles(0xc0000ee000, 0xc000102030, 0x24, 0x91f800, 0xc0000a6020)
ibazel/ibazel.go:502 +0x5d
main.(*IBazel).iteration(0xc0000ee000, 0x879818, 0x3, 0xc000135e10, 0xc000082e80, 0x1, 0x1, 0x7ffd2a9df0b9, 0xd)
ibazel/ibazel.go:310 +0x947
main.(*IBazel).loop(0xc0000ee000, 0x879818, 0x3, 0xc000135e10, 0xc000082e80, 0x1, 0x1, 0x0, 0x0)
ibazel/ibazel.go:270 +0xfb
main.(*IBazel).Run(0xc0000ee000, 0x7ffd2a9df0b9, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
ibazel/ibazel.go:252 +0xe3
main.handle(0xc0000ee000, 0x7ffd2a9df0b5, 0x3, 0xc000084170, 0x1, 0x1)
ibazel/main.go:193 +0x12d
main.main()
ibazel/main.go:178 +0x2f9

**Comment by afifalfiano** [comment]
I was updated my package.json

==========================
{
  "name": "angular9",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "postinstall": "ngcc --properties es2015 browser module main",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular/bazel": "~9.1.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@bazel/bazel": "2.1.0",
    "@bazel/bazelisk": "^1.4.0",
    "@bazel/ibazel": "0.13.1",
    "@bazel/karma": "1.5.0",
    "@bazel/protractor": "1.5.0",
    "@bazel/rollup": "1.5.0",
    "@bazel/terser": "1.5.0",
    "@bazel/typescript": "1.5.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "history-server": "1.3.1",
    "html-insert-assets": "0.5.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-firefox-launcher": "1.2.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "karma-requirejs": "1.1.0",
    "karma-sourcemap-loader": "0.3.7",
    "protractor": "5.4.2",
    "requirejs": "2.3.6",
    "rollup": "1.27.5",
    "rollup-plugin-commonjs": "10.1.0",
    "rollup-plugin-node-resolve": "5.2.0",
    "terser": "4.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}

**Comment by achew22** [comment]
Interesting, could you run `bazel info` and see what the output from that is. It looks like that's failing for some reason, but `ibazel` eats the output so we can't see it.

**Comment by afifalfiano** [comment]
This is output from bazel info command

==================================== 
asus  ~/Documents/Bazel_Research/angular9   staging ●✚  bazel info 
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
bazel-bin: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/bin
bazel-genfiles: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/bin
bazel-testlogs: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/command.log
committed-heap-size: 93MB
execution_root: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project
gc-count: 8
gc-time: 107ms
install_base: /home/asus/.cache/bazel/_bazel_asus/install/5f3a0e9dbcdf67475c08459b42b1f93c
java-home: /home/asus/.cache/bazel/_bazel_asus/install/5f3a0e9dbcdf67475c08459b42b1f93c/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.2+7-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 1220MB
output_base: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef
output_path: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out
package_path: %workspace%
release: release 2.1.0
repository_cache: /home/asus/.cache/bazel/_bazel_asus/cache/repos/v1
server_log: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/java.log.asus-virtualbox.asus.log.java.20200605-152342.3117
server_pid: 3117
used-heap-size: 42MB
workspace: /home/asus/Documents/Bazel_Research/angular9
 asus  ~/Documents/Bazel_Research/angular9   staging ●✚ 

**Comment by afifalfiano** [comment]
So, what I should do to fix this error?

**Comment by achew22** [comment]
Can you post the error you're getting inside of a code fence? It's much easier to parse.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by afifalfiano** [comment]
```
asus  ~/Documents/Bazel_Research/angular9   staging ●✚  bazel info
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
bazel-bin: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/bin
bazel-genfiles: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/bin
bazel-testlogs: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out/k8-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/command.log
committed-heap-size: 93MB
execution_root: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project
gc-count: 8
gc-time: 107ms
install_base: /home/asus/.cache/bazel/_bazel_asus/install/5f3a0e9dbcdf67475c08459b42b1f93c
java-home: /home/asus/.cache/bazel/_bazel_asus/install/5f3a0e9dbcdf67475c08459b42b1f93c/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.2+7-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 1220MB
output_base: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef
output_path: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/execroot/project/bazel-out
package_path: %workspace%
release: release 2.1.0
repository_cache: /home/asus/.cache/bazel/_bazel_asus/cache/repos/v1
server_log: /home/asus/.cache/bazel/_bazel_asus/df0799ed243914fbb812a54563bb98ef/java.log.asus-virtualbox.asus.log.java.20200605-152342.3117
server_pid: 3117
used-heap-size: 42MB
workspace: /home/asus/Documents/Bazel_Research/angular9
```

**Comment by achew22** [comment]
Okay, I looked through your errors outputs again. It looks like you have a flag set in your rc file. `--incompatible_disallow_bzl_load_after_statement` that error message is visible to see in your scroll back when you run your command in one of your screenshots.

**Comment by afifalfiano** [comment]
So I have to disable the command? that is right?

**Comment by afifalfiano** [comment]
Wohoo, thank @achew22 , I only disable the command and ibazel can be running well 😁

![image](https://user-images.githubusercontent.com/47497276/84082550-3d1e1d00-aa0a-11ea-96d0-142c9bf6bb69.png)
