### ISSUE TITLE
Unable to create issue template

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-watcher#409]
@aiuto, since you've been so helpful in previous issues and there doesn't seem to be anyone else who can help.

I would like to add an [issue template](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to the repo, but seem to not have the permissions. Is it possible to grant me the permissions to create an issue/PR template?

**Comment by aiuto** [comment]
I went through the setup for a bug report.   Do you have the ability to edit that template?  I see a link on the new issue page like [edit templates]

**Comment by achew22** [comment]
@aiuto, thanks for helping out! Looks like this will work for now since you turned the setting on.
