### ISSUE TITLE
[Request] APT package for iBazel

### ISSUE THREAD

**Issue by davidlee1435** [bazelbuild/bazel-watcher#418]
**Describe the bug**
Hey folks, are there any plans to upload iBazel to APT? I'd like to run iBazel in an Ubuntu Docker container and install with `apt-get`.

**Comment by achew22** [comment]
I've asked the bazel team several times to help me get packaged in the apt repo, but there doesn't seem to be interest. If you would like to take up the mantle, I would be happy to help in any way I can.

**Comment by davidlee1435** [comment]
No worries, I'll just install the binary via the Github releases.
