### ISSUE TITLE
Clear the terminal output before every run

### ISSUE THREAD

**Issue by franciscocpg** [bazelbuild/bazel-watcher#423]
Is there a way to clear the terminal output before every run?

I've tried an approach using `.bazel_fix_commands.json` but it clears the terminal output after running the tests.
```json
[
  {
    "regex": "go_default_test",
    "command": "clear"
  }
]
```

**Comment by achew22** [comment]
Hey @franciscocpg this seems like an entirely reasonable feature request. I don't think that there is a good hook for this right now unfortunately, but I think it could pretty easily be added. What could I do to help make a PR for this possible?

**Comment by franciscocpg** [comment]
Hi @achew22.

I'm not sure if it makes sense to put it in `.bazel_fix_commands.json` because I want it to run the command before each execution. Maybe add a command flag like `--command_before_run` and then use it to run the command here?
https://github.com/bazelbuild/bazel-watcher/blob/51d9fe43bf520ce40a3c22affc960fd094fce51d/ibazel/live_reload/server.go#L76

Does it make sense?
