### ISSUE TITLE
ibazel should pass unknown flags to the underlying bazel command

### ISSUE THREAD

**Issue by pascalfleury** [bazelbuild/bazel-watcher#426]
**Describe the bug**
Useful flags are not passed to the underlying bazel command that ibazel runs.

**Reproduction instructions**
ibazel test -c dbg --cxxopt=-std=c++17 --test_output=errors <target>

1. use a repository that is built with bazel
2. make sure ibazel is available
3. Run something like the command above:
     ibazel test -c dbg --cxxopt=-std=c++17 --test_output=errors <target>
4. Notice that a) flags are not passed, and b) they interfere. Here is an output on my version:
$ ibazel test -c dbg --cxxopt=-std=c++17 --test_output=errors mime:mime-db_test
iBazel [10:22PM]: Querying for files to watch...
Loading: 0 packages loaded
ERROR: Error while parsing 'buildfiles(deps(set(dbg --cxxopt=-std=c++17 mime:mime-db_test)))': syntax error at '- - cxxopt'
Loading: 0 packages loaded
Loading: 0 packages loaded
iBazel [10:22PM]: Bazel query failed: exit status 2
Loading: 0 packages loaded
ERROR: Error while parsing 'kind('source file', deps(set(dbg --cxxopt=-std=c++17 mime:mime-db_test)))': syntax error at '- - cxxopt'
Loading: 0 packages loaded
Loading: 0 packages loaded
iBazel [10:22PM]: Bazel query failed: exit status 2
iBazel [10:22PM]: Testing dbg --cxxopt=-std=c++17 mime:mime-db_test
ERROR: While parsing option -c --test_output=errors: Not a valid compilation mode: '--test_output=errors' (should be fastbuild, dbg or opt)
iBazel [10:22PM]: Build error: exit status 2

**Expected behavior**
ibazel passes e.g. --test_output=errors to bazel and the errors in tests get shown.

**`bazel query --output=build //path/to:target`**

**Version (please complete the following information):**
 - OS: Linux, Ubuntu 20.04
 - Browser not relevant
 - ibazel Version: git head at commit 51d9fe43bf520ce40a3c22affc960fd094fce51d
 - Bazel 3.6.0

**Comment by achew22** [comment]
There is a preexisting list of flags that are passed down. If you have additional flags that you would like to have passed, please add them to the list here:

https://github.com/bazelbuild/bazel-watcher/blob/51d9fe43bf520ce40a3c22affc960fd094fce51d/ibazel/main.go#L29-L64

--------------------------------

> Expected behavior
> ibazel passes e.g. --test_output=errors to bazel and the errors in tests get shown.
> `bazel query --output=build //path/to:target`

I think the issue here might be that you used `--output` instead of `--test_output`. The later is in the list of flags that are properly handled.

**Comment by pascalfleury** [comment]
Is it known that tests fail when running, in a freshly cloned repo ?

$ *rm -rf bazel-watcher*
$ *git clone https://github.com/bazelbuild/bazel-watcher.git
<https://github.com/bazelbuild/bazel-watcher.git>*
Clonage dans 'bazel-watcher'...
remote: Enumerating objects: 1753, done.
remote: Total 1753 (delta 0), reused 0 (delta 0), pack-reused 1753
Réception d'objets: 100% (1753/1753), 547.81 Kio | 1.34 Mio/s, fait.
Résolution des deltas: 100% (1020/1020), fait.
$ *cd bazel-watcher/*
$ bazel test //...
Starting local Bazel server and connecting to it...
INFO: Analyzed 44 targets (91 packages loaded, 7964 targets configured).
INFO: Found 30 targets and 14 test targets...
FAIL: //e2e/termination:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/termination/go_default_test/test.log)

FAIL: //e2e/vim:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/vim/go_default_test/test.log)

FAIL: //e2e/profiler:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/profiler/go_default_test/test.log)

FAIL: //e2e/simple:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/simple/go_default_test/test.log)

FAIL: //e2e/live_reload:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/live_reload/go_default_test/test.log)

FAIL: //e2e/override_repository:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/override_repository/go_default_test/test.log)

FAIL: //e2e/output_runner:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/output_runner/go_default_test/test.log)

FAIL: //e2e/error:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/error/go_default_test/test.log)

FAIL: //e2e/local_repository:go_default_test (see
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/local_repository/go_default_test/test.log)

INFO: Elapsed time: 395.701s, Critical Path: 90.27s
INFO: 12 processes: 1 internal, 2 linux-sandbox, 9 local.
INFO: Build completed, 9 tests FAILED, 12 total actions
//bazel:go_default_test                                         (cached)
PASSED in 0.1s
//ibazel:go_default_test                                        (cached)
PASSED in 5.3s
//ibazel/command:go_default_test                                (cached)
PASSED in 33.3s
//ibazel/log:go_default_test                                    (cached)
PASSED in 0.2s
//ibazel/output_runner:go_default_test                          (cached)
PASSED in 0.6s
//e2e/error:go_default_test
FAILED in 39.4s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/error/go_default_test/test.log

//e2e/live_reload:go_default_test
FAILED in 33.1s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/live_reload/go_default_test/test.log

//e2e/local_repository:go_default_test
FAILED in 34.9s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/local_repository/go_default_test/test.log

//e2e/output_runner:go_default_test
FAILED in 39.1s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/output_runner/go_default_test/test.log

//e2e/override_repository:go_default_test
FAILED in 26.2s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/override_repository/go_default_test/test.log

//e2e/profiler:go_default_test
FAILED in 22.7s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/profiler/go_default_test/test.log

//e2e/simple:go_default_test
FAILED in 68.6s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/simple/go_default_test/test.log

//e2e/termination:go_default_test
FAILED in 88.8s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/termination/go_default_test/test.log

//e2e/vim:go_default_test
FAILED in 33.2s
 /home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/vim/go_default_test/test.log


Executed 9 out of 14 tests: 5 tests pass and 9 fail locally.
INFO: Build completed, 9 tests FAILED, 12 total actions
$

All the errors seem to be of this type:

$ more
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/e2e/live_reload/go_default_test/test.log

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //e2e/live_reload:go_default_test
-----------------------------------------------------------------------------

=== RUN   TestLiveReload
   TestLiveReload: live_reload_test.go:71: ibazel invoked as:
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/bin/e2e/live_reload/linux_amd64_stripped/go_default_test.runfile

s/__main__/ibazel/linux_amd64_pure_stripped/ibazel
--bazel_path=/usr/bin/bazel --log_to_file=/tmp/ibazel_output.857189451.log
--graceful_termination_wait_duration=1s run //:live_reload
   TestLiveReload: live_reload_test.go:74: Expected iBazel output after 20s
to be:
       Wanted [Live reload url: http://.+:\d+], got []
   TestLiveReload: live_reload_test.go:74: Stderr: []
       iBazelStderr: [iBazel [9:16PM]: Running `bazel info`... it's being a
little slow
       ]
   TestLiveReload: live_reload_test.go:76: Output: ''
   TestLiveReload: live_reload_test.go:79: Output was empty. Expected at
least some output
--- FAIL: TestLiveReload (23.03s)
=== RUN   TestNoLiveReload
   TestNoLiveReload: live_reload_test.go:148: ibazel invoked as:
/home/fleury/.cache/bazel/_bazel_fleury/d831baee0274baee2562fb1f08ba037f/execroot/__main__/bazel-out/k8-fastbuild/bin/e2e/live_reload/linux_amd64_stripped/go_default_test.runf

iles/__main__/ibazel/linux_amd64_pure_stripped/ibazel
--bazel_path=/usr/bin/bazel --log_to_file=/tmp/ibazel_output.213795630.log
--graceful_termination_wait_duration=1s run //:no_live_reload
--- PASS: TestNoLiveReload (9.60s)
FAIL


--Pascal

**Comment by achew22** [comment]
The [CI system](https://buildkite.com/bazel/bazel-watcher/builds?branch=master) reports that we've been green since some time in July.

```
$ cd $(mktemp -d) && git clone https://github.com/bazelbuild/bazel-watcher.git && cd bazel-watcher && bazel test //...
Cloning into 'bazel-watcher'...
remote: Enumerating objects: 1753, done.
remote: Total 1753 (delta 0), reused 0 (delta 0), pack-reused 1753
Receiving objects: 100% (1753/1753), 547.81 KiB | 11.66 MiB/s, done.
Resolving deltas: 100% (1020/1020), done.
Starting local Bazel server and connecting to it...
INFO: Analyzed 44 targets (90 packages loaded, 7964 targets configured).
INFO: Found 30 targets and 14 test targets...
[96 / 514] 16 actions, 15 running
[116 / 514] 16 actions running
[124 / 514] 16 actions running
    Compiling external/com_google_protobuf/src/google/protobuf/descriptor.cc [for host]; 19s linux-sandbox
[125 / 514] 16 actions running
INFO: Elapsed time: 458.194s, Critical Path: 119.63s
INFO: 568 processes: 559 linux-sandbox, 9 local.
INFO: Build completed successfully, 626 total actions
//bazel:go_default_test                                                  PASSED in 0.2s
//e2e/error:go_default_test                                              PASSED in 26.2s
//e2e/live_reload:go_default_test                                        PASSED in 23.0s
//e2e/local_repository:go_default_test                                   PASSED in 17.9s
//e2e/output_runner:go_default_test                                      PASSED in 26.1s
//e2e/override_repository:go_default_test                                PASSED in 14.1s
//e2e/profiler:go_default_test                                           PASSED in 20.7s
//e2e/simple:go_default_test                                             PASSED in 68.0s
//e2e/termination:go_default_test                                        PASSED in 82.3s
//e2e/vim:go_default_test                                                PASSED in 23.1s
//ibazel:go_default_test                                                 PASSED in 5.3s
//ibazel/command:go_default_test                                         PASSED in 0.2s
//ibazel/log:go_default_test                                             PASSED in 0.3s
//ibazel/output_runner:go_default_test                                   PASSED in 0.2s

Executed 14 out of 14 tests: 14 tests pass.
INFO: Build completed successfully, 626 total actions
```

May I ask what `bazel version` reports?

**Comment by pascalfleury** [comment]
it's the stock version that comes with Ubuntu 20.04.1 LTS (apt install bazel
)


$ bazel version

Build label: 3.6.0

Build target:
bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar

Build time: Tue Oct 6 13:11:20 2020 (1601989880)

Build timestamp: 1601989880

Build timestamp as int: 1601989880

**Comment by achew22** [comment]
Hrm... I tried looking that version up in the Ubuntu but couldn't find it. It looks like Ubuntu doesn't have Bazel in its [package manager](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=bazel)? Is it possible you installed it from the [Bazel apt repo](https://docs.bazel.build/versions/3.7.0/install-ubuntu.html)?

On the debugging front. Can you try a `bazel clean --expunge` in that repo then `bazel test //...`? I've seen some cache invalidation issues in the past that might be related to this? But I'm mostly at a loss. I would love to fix whatever's going on, but I can't reproduce it on any of my boxes (Ubuntu 18.04, 20.04, 20.10, Mac OSx, or CI). Do you have any clues on how I can get it to fail in this way?

**Comment by djmarcin** [comment]
> There is a preexisting list of flags that are passed down. If you have additional flags that you would like to have passed, please add them to the list here:

I don't think this strategy is going to work long-term. https://docs.bazel.build/versions/master/configurable-attributes.html are arbitrary and user-defined, so it's not possible to maintain a list of flags to pass through.

`ibazel` should probably adopt something like the `--` syntax used by other utilities to mean "all flags after this point are passed blindly to the underlying bazel process", e.g. `ibazel build //foo:bar -- --//:some_feature=enabled`

**Comment by achew22** [comment]
@djmarcin, I totally agree. I've got pretty robust e2e testing in place and would love to get a patch to improve it. What can I do to make it simple enough that you could contribute a patch?

**Comment by djmarcin** [comment]
I might be able to look at this sometime this month. Let me know if there’s
anything specific about implementation or testing you had in mind.

**Comment by djmarcin** [comment]
Sorry for not circling back. This actually wasn't very straightforward (some options need to be passed in different places, e.g. `bazel <some go here> build <others go here>`) so I worked around it by just putting options into a custom `.bazelrc` instead.
