### ISSUE TITLE
ibazel does not monitor the WORKSPACE file

### ISSUE THREAD

**Issue by pascalfleury** [bazelbuild/bazel-watcher#427]
**Describe the bug**
ibazel does not react when the WORKSPACE file changes.

**Reproduction instructions**
Any repository that has some dependencies specified in the WORKSPACE file.

1. build a target that depends on an external repository
2. run `ibazel build <target>`
3. Edit the `WORKSPACE` e.g. to change the tag or commit to which a git repository is sync'd.
4. Notice no reaction from `ibazel`

**Expected behavior**
`ibazel` does what `bazel` would do, i.e. sync the repository, and rebuild the target.

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser not relevant
 - ibazel Version from git, commit 51d9fe43bf520ce40a3c22affc960fd094fce51d
 - Bazel 3.6.0

**Comment by achew22** [comment]
PS: If this is the same Pascal Fleury from Google Zurich, it's great to see you! Hope you're enjoying ibazel.

**Comment by pascalfleury** [comment]
it is me :-)

I'll give it a shot for the fix.

--Pascal

Le ven. 16 oct. 2020 à 23:27, Andrew Z Allen <notifications@github.com> a
écrit :

**Comment by andremarianiello** [comment]
Is there a way to un-stale this issue? @pascalfleury Are you still working on this?
