### ISSUE TITLE
Permission denied error with output runner

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/bazel-watcher#434]
**Describe the bug**

Output runner is logging this error:

```
iBazel [1:31PM]: Error starting process: fork/exec /tmp/bazel_script_path180801963: permission denied
iBazel [1:31PM]: Run start failed fork/exec /tmp/bazel_script_path180801963: permission denied
```

**Reproduction instructions**

- Create an output runner config like the one in the README
- Edit a `BUILD` file for a Go target so that it's missing a dependency
- Try to build the target
- Gazelle should be run
- It does look like Gazelle is run, but I'm also getting this error. Not sure whether this is a problem, but it's mildly concerning.

**Expected behavior**
The output runner should execute the command without showing this permission denied error.

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - ibazel 0.13.2
 - Bazel version
```
Bazelisk version: v1.6.1
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
```

**Additional context**

I am using a workspace override and running `ibazel` from a workspace directory different from the one that has the output runner config. Maybe that could be part of the problem? (I do see that `gazelle` gets run on the wrong workspace -- it should be run within the local override workspace, not the one that depends on the local override... maybe that's a separate bug?).

**Comment by achew22** [comment]
Out of curiosity, did this happen after the `build` stage failed?

**Comment by simmonmt** [comment]
@achew22 for me, yes.

```
iBazel [9:20AM]: Notifying of changes
Loading:
Loading: 0 packages loaded
Analyzing: target //12/src:solution (0 packages loaded, 0 targets configured)
INFO: Analyzed target //12/src:solution (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /home/simmonmt/src/aoc/2020/12/src/BUILD.bazel:3:10: GoCompilePkg 12/src/solution.a failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src 12/src/main.go -arc ... (remaining 23 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src 12/src/main.go -arc ... (remaining 23 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
	/home/simmonmt/.cache/bazel/_bazel_simmonmt/bd883a2a6bca35f79faeb7d08fef27b6/sandbox/linux-sandbox/29/execroot/__main__/12/src/main.go: import of "github.com/simmonmt/aoc/2020/common/intmath"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //12/src:solution failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.215s, Critical Path: 0.09s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
iBazel [9:20AM]: Error starting process: fork/exec /tmp/bazel_script_path163498207: permission denied
```

Bazel 3.7.1
ibazel 35ab9a9 (current HEAD)

FWIW this problem was happening with an ancient version of ibazel as well (from 2019). I noticed that ibazel was ancient, updated to HEAD, rebuilt, and the new version has the same problem.

```
$ cat .bazel_fix_commands.json
[{
  "regex": "^Check that imports in Go sources match importpath attributes in deps.$",
  "command": "bazel",
  "args": ["run", "//:gazelle_fix"]
}]
```

In my case Gazelle is **not** getting run.

Also strange, ibazel will run Gazelle if it notices a missing dependency on its **first** run, but will emit the above error on subsequent runs.

That is,

1. I add import without dep
2. I start ibazel, ibazel notices missing dep error, runs gazelle
3. I add another import without dep
4. Already-running ibazel notices change to source file, runs bazel again, notices missing dep error (output snippet above), tries to run gazelle, emits error

**Comment by achew22** [comment]
Is there any chance I could have you add a test case into `//e2e` that demonstrates this?

**Comment by simmonmt** [comment]
@achew22 sorry for the misdirection. It looks like the error message was a red herring. I've separately reported the higher-level problem I'm seeing in https://github.com/bazelbuild/bazel-watcher/issues/447
