### ISSUE TITLE
Modify project permissions

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-watcher#436]
@philwo thank you so much for offering to help modify the Bazel Watcher project permissions and thank you for giving the community a forum for conversation. I really love the project and want to see it as great as it can be.

Thanks so much!

**Comment by philwo** [comment]
@achew22 You're admin of this repo now. Please let me know if you need anything else. 😊

**Comment by achew22** [comment]
Looks like it was successful. I'm very glad I don't have to bug Tony any more. Please convey my thanks to him for all the help he provided me. Thank you so much to both of you!
