### ISSUE TITLE
MacOS: Too many open files (still)

### ISSUE THREAD

**Issue by kylecordes** [bazelbuild/bazel-watcher#438]
**Describe the bug**

A recent change improved file watching. But nonetheless, the MacOS Too many open files there are still happens… At least on my machine. See closed issues #109 and #402.

**Reproduction instructions**

https://github.com/kylecordes/ibazel_repro

1. `git clone git@github.com:kylecordes/ibazel_repro.git`
2. `yarn run serve`  (which runs ibazel)
3. "too many open files"

**Expected behavior**

Works when there are lots of files to watch.

**Version (please complete the following information):**
 - MacOS 10.15.7
 - Browser n/a
 - ibazel Version: v0.14.0
 - Bazel version:

```
Build label: 3.7.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:31:07 2020 (1603200667)
```
 
**Additional context**

I used a tool I wrote for other reasons, "angular-stress-test", to keep making the project larger until it failed. `npm i -g angular-stress-test`.

**Comment by kylecordes** [comment]
Looks like @achew22 and @joeljeske have improved this already in past issues.

**Comment by achew22** [comment]
How many files are you looking to watch?

**Comment by joeljeske** [comment]
Actually, my PR to fix this on MacOS never landed, I think it's still open. I couldn't resolve a failing test. I would love some help with it.

**Comment by joeljeske** [comment]
Nope, it was auto closed. 

https://github.com/bazelbuild/bazel-watcher/pull/406

I ended up having to fork since we needed this change. I would love to land it upstream though.

**Comment by achew22** [comment]
@joeljeske the last comment on that thread was you saying:

> Thanks @achew22 ill push up a change to remove that test here in a bit.

How can I help push this over the line? I've reopened the PR if you'd like to move discussion over there.

**Comment by joeljeske** [comment]
Oh shoot you're right. I forgot that's where we ended up. I'll try to find time The next couple days to rebase and see about removing that test. Sorry for dropping the ball here!

**Comment by kylecordes** [comment]
@achew22 Thousands; but I don't know exactly how many offhand.

I haven’t dug into the APIs for file notifications in a few years, but I was under the impression a reasonably optimal implementation would be indifferent to the number of files on all major platforms. (Though the number of directories may still be limited.)

**Comment by joeljeske** [comment]
Another note, when I was adding FSEvents, I noted that the current algorithm was to stat each watched dir before watch mode startup, which also caused perf issues on some systems. I wasn't sure the reasoning of this, and definitely when using FSEvents it shouldn't be necessary. 

@achew22 any idea why this is needed?

**Comment by achew22** [comment]
Does it stat in `FSEvents` and in `FSNotify`?

**Comment by joeljeske** [comment]
No, it's in iBazel, would we be able to remove it?

ibazel/ibazel.go:518

**Comment by achew22** [comment]
If you'd like to refactor that codepath to require fewer invocations of `stat` then I'd be happy to accept it, provided the e2e tests pass, but let's do that in another PR if that's okay.

**Comment by joeljeske** [comment]
I updated that PR and tests passed. @kylecordes if you could try that branch and let me know if that fixes your issue that would be helpful. Thanks!

**Comment by kylecordes** [comment]
@joeljeske Yes, on that PR branch, commit 3d730211ba6c6b87d78841702a81998d6bddaa88 as I write this, ibazel now handles my repro example project without error. Thanks!
