### ISSUE TITLE
ibazel --run_output behaves inconsistently for bazel run

### ISSUE THREAD

**Issue by simmonmt** [bazelbuild/bazel-watcher#447]
**Describe the bug**

`ibazel run --run_output` enables the `run_output` machinery unconditionally for the first iteration (start), but only enables it conditionally for the second iteration (notify). It only appears to work for the notify iteration when `ibazel_notify_changes` is set in the requested rule.

This causes unexpected behavior when ibazel is used to run a command that has not specifically requested change notification.

**Reproduction instructions**
https://github.com/simmonmt/advent-of-code

1. `git clone https://github.com/simmonmt/advent-of-code`
1. `cd advent-of-code/2020`
1. `ibazel --run_output --run_output_interactive=false run 13/src/solution -- --input  13/input.txt`
1. Edit `13/src/main.go` -- import `github.com/simmonmt/aoc/2020/common/pos` and add a var `p=pos.P2{}`.

**Expected behavior**

I expected gazelle to be run, per the directive in advent-of-code/2020/.bazel_fix_commands.json, when ibazel re-ran (in notify mode) after the source file edit.

It does not run because 2020/13/src:solution has no `ibazel_notify_changes` tag.

This is very confusing because run_output will be run the first time I run ibazel, only to mysteriously not be run the second time. There's no error message to tell me that it's not going to do the run_output magic even though I've passed --run_output.

Possible fixes:
1. Always use run_output when the user invokes as `ibazel run --run_output` -- don't change behavior based on the presence of a tag. Or add a flag to force it, though arguably there are too many run_output flags as it is.
1. Exit with an error if the user invokes as `ibazel run --run_output` on a target that doesn't have the tag. The user has specifically asked for a thing, and ibazel is explicitly choosing not to do that thing.

**Version (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: n/a
 - ibazel Version: [35ab9a9](https://github.com/bazelbuild/bazel-watcher/commit/35ab9a9994dea4bc2822039c3617da28317094f0)
 - Bazel version:

```
Build label: 3.7.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 24 17:38:30 2020 (1606239510)
Build timestamp: 1606239510
Build timestamp as int: 1606239510
```
 
**Additional context**

**Comment by simmonmt** [comment]
I acknowledge that this behavior is documented in the README. My assertion is that the behavior is confusing, and assumes that users read the docs (which we/they don't). It wouldn't be quite so confusing if ibazel didn't do run_output parsing in the startup phase.

**Comment by achew22** [comment]
I think I agree with your description of this as non-intuitive behavior. Likely even behavior that has tripped me up by mistake in the past. I would be very happy to accept a PR to make the flag behavior persist after the first run.
