### ISSUE TITLE
Support ibazel coverage

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/bazel-watcher#448]
Hey team, we're looking at integrating coverage into our repository with bazel and we're after continuous updates to our coverage.
Currently we need to develop our tests with `ibazel run :target` then separately we run `bazel coverage :target`, however ideally we'd just run `ibazel coverage :target` to get fast updates to our code coverage

**Comment by achew22** [comment]
Oh how I wish there was a team behind this 🤣. Sorry, it's just me.

Alright, here is how I would go about doing this:

1) Add a new `Test` method into `ibazel.go` called `Coverage`

  https://github.com/bazelbuild/bazel-watcher/blob/35ab9a9994dea4bc2822039c3617da28317094f0/ibazel/ibazel.go#L264-L267

2) Add a new case statement to handle `coverage` being passed in on the command line:

  https://github.com/bazelbuild/bazel-watcher/blob/35ab9a9994dea4bc2822039c3617da28317094f0/ibazel/main.go#L198-L199

3) Add to the e2e helper a new method `Coverage`

  https://github.com/bazelbuild/bazel-watcher/blob/35ab9a9994dea4bc2822039c3617da28317094f0/e2e/ibazel.go#L58-L61

4) And the associated internal `coverage` function based on

  https://github.com/bazelbuild/bazel-watcher/blob/35ab9a9994dea4bc2822039c3617da28317094f0/e2e/ibazel.go#L266-L283

5) Add a new test case called `TestSimpleCoverage` shaped like this:

  https://github.com/bazelbuild/bazel-watcher/blob/35ab9a9994dea4bc2822039c3617da28317094f0/e2e/simple/simple_test.go#L65-L71

  Please note that you'll probably need to add an `sh_test` to the test fixture. The fixtures are formatted as [txtar](https://godoc.org/golang.org/x/vgo/vendor/cmd/go/internal/txtar#:~:text=Txtar%20format,the%20next%20file%20marker%20line).

 https://github.com/bazelbuild/bazel-watcher/blob/35ab9a9994dea4bc2822039c3617da28317094f0/e2e/simple/simple_test.go#L15-L57

It looks like I don't have any test coverage of `ibazel test` in there. If you were feeling like a total boss it would be amazing if you did the `e2e` stuff also for a new test.
