### ISSUE TITLE
Idea: run initial bazel query in the background

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/bazel-watcher#451]
IIUC, `ibazel` can be slow on the first execution because of the `bazel query` that it has to run to determine which files to watch.

Would it improve performance at all if this `bazel query` were instead run _after_ the initial build?

**Comment by achew22** [comment]
Hey @bduffany, thanks for the idea!

> IIUC, ibazel can be slow on the first execution because of the bazel query that it has to run to determine which files to watch.

Two things spring to mind here:

1. It's true that an invocation of `ibazel build foo` causes  `bazel query` to be run, but I would be interested in seeing some benchmarking on this before we declare it a performance horror. I have a funny feeling that the `bazel query` that `ibazel` runs is very likely to be **exactly** what bazel needs to run to figure out which files it needs to build. The initial bazel query run by `ibazel` just finds a list of the source files that need to be watched (aka the files that need to be compiled) and I believe the query would just pre-warm the cache for the inevitable `bazel` `build`/`test`/`run`.

1. There is also the tricky case of a long running `bazel test`. In the proposed world, the user would run `ibazel test`, the `bazel test` is running for 5 mintes, but while it's running the user modifies a file. ibazel would have no visibility into that file change and wouldn't know to retrigger the test.
