### ISSUE TITLE
Publish v0.15.0 to NPM

### ISSUE THREAD

**Issue by herman-rogers** [bazelbuild/bazel-watcher#460]
Just a quick question - will ibazel v0.15.0 be published to npm?

**Comment by achew22** [comment]
Yeah, the intent is to fix it up. Unfortunately $DAYJOB is totally insane. If I do not do a 0.15.0 release on NPM in the next week please ping again.

**Comment by mc0** [comment]
A friendly ping :). It looks like the brew recipe is also stale at 0.13.1.

**Comment by herman-rogers** [comment]
@bazel/ibazel is at version 0.15.6 on npm. Thanks @achew22 !
