### ISSUE TITLE
GitHub actions are failint

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-watcher#467]
There appears to be something wrong with the GitHub actions setup for getting things stamped.

**Comment by achew22** [comment]
```
fatal: No names found, cannot describe anything.
```

I added the fetch-depth thing to no avail but then I realized there are 2 of them. I'm going to try `--always` in the stamp script which should make it work no matter what (even if it's tagged wrong, which would be bad but would be educational)

**Comment by joeljeske** [comment]
I think the GH Actions is not fetching the tags locally. I think its doing a shallow clone of the SHA but without any branches/tags in the cloned repo.

**Comment by joeljeske** [comment]
Do you want to try adding fetch-depth:0 to the checkout? 
https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches

Alternatively we could try a post-checkout fetch of the tags or unshallow the clone?

**Comment by achew22** [comment]
Here is the result of adding `fetch-depth:0`

https://github.com/bazelbuild/bazel-watcher/runs/2167896165?check_suite_focus=true

But it doesn't look like it showed up on the npm side

https://www.npmjs.com/package/@bazel/ibazel

Thanks for helping me get this closer!

**Comment by joeljeske** [comment]
For better or worse, I hade made it only publish to npm if it was the result of creating a new GH release
https://github.com/bazelbuild/bazel-watcher/blob/master/.github/workflows/release.yaml#L116

**Comment by joeljeske** [comment]
You could remove that condition, or try to create a formal GH release (not just a tag and manually running it)

**Comment by joeljeske** [comment]
That condition corresponds with the condition to upload the assets to the real GH release
https://github.com/bazelbuild/bazel-watcher/blob/master/.github/workflows/release.yaml#L63

**Comment by achew22** [comment]
Let's try doing a full release! https://github.com/bazelbuild/bazel-watcher/actions/runs/677723048

**Comment by achew22** [comment]
That looks VERY promising! Now to figure out how to allow a service account to deploy when you have two factor turned on... this'll be fun...

**Comment by achew22** [comment]
I think this is the one https://github.com/bazelbuild/bazel-watcher/actions/runs/677790605

**Comment by achew22** [comment]
I sort of had the idea that this would fix it

![image](https://user-images.githubusercontent.com/37206/112071685-f1baa280-8b35-11eb-871f-11385e9a99c7.png)

but apparently not? Maybe NPM has some latency between that setting being changed and taking effect. I'll try a release again later.

**Comment by joeljeske** [comment]
I don’t think you want 2fa on the publishing token at all. Option 1?

https://github.com/bazelbuild/bazel-watcher/pull/456#discussion_r565758390

**Comment by achew22** [comment]
If I pick option 1 that will disable the requirement that MFA be turned on for manual pushes which means that someone who guesses my password alone would be able to publish. Option 2 seems like the correct one since we are using automation tokens and those automation tokens are not bound to MFA?

**Comment by achew22** [comment]
As a quick test I tried releasing `v0.15.5` with MFA completely disabled. It is now reenabled.

Lessons learned from this test:

* It doesn't matter what the setting is, which means it is probably a setting that comes from the `@bazel` organization.
* I have no idea who owns the `@bazel` organization so I can ask them to change this setting 😦

**Comment by joeljeske** [comment]
Have you tried the steps I put here? https://github.com/bazelbuild/bazel-watcher/pull/456#discussion_r565758390

I think you need a new explicit token for automation.

**Comment by achew22** [comment]
Yes, I have generated an auth token.

![image](https://user-images.githubusercontent.com/37206/112227764-c6978800-8bf5-11eb-8dea-b45060550bae.png)

Did I miss a step in that?

**Comment by achew22** [comment]
Since I don't have a good way to validate the kind of token behind that, I'm going to try generating a new automation token and see what happens.

**Comment by achew22** [comment]
I think that might have been it! Thanks so much @joeljeske for all your hard work on this. I really appreciate it.
