### ISSUE TITLE
Aborting an in progress build when a new one is needed

### ISSUE THREAD

**Issue by mistic** [bazelbuild/bazel-watcher#478]
I believe this is more a suggestion to improve `iBazel` then a bug report. 

I think it will be very useful to abort an in progress build when we got the information a new one is needed. For instance, I had `iBazel` running, switched to master, and then pulled upstream. Unfortunately `iBazel` started running the build as soon as I switched branches which means it was running a bunch of builds which were immediately invalidated by the pull from upstream so I needed to kill `iBazel` and restart it to avoid waiting an extra 100+sec for it to rebuild a ton.

What do you think about this @achew22 ?

**Comment by achew22** [comment]
Hey @mistic,

Just to sketch out how I would think about this:

In my experience, things that are controlled through environment variables have very poor discoverability unless they're required and cause error output if they aren't provided so I think I'd like to stay away from that. My preference would be to make it similar to `ibazel_skip_live_reload` et al. that way it can be done on a per-target basis in the build graph without the need to specify on a regular basis.

You'd need to augment

https://github.com/bazelbuild/bazel-watcher/blob/4683e4f3788bb3312ee82dbdf937aa1c459c0de9/ibazel/ibazel.go#L391-L393

to track your new `ibazel_abort_compilation_early` (not suggesting a name, just needed something in there as a placeholder).

If I understand things correctly, what you'd like to do is modify the state machine to have an additional transition from the RUN state that is able to short circuit the test/build process, correct?

To write out a rough outline of this, I think you'd be extending this code to do a select on a set of channels:

https://github.com/bazelbuild/bazel-watcher/blob/4683e4f3788bb3312ee82dbdf937aa1c459c0de9/ibazel/ibazel.go#L324-L330

where the `select` is switching for events either from a i.sourceFileWatcher.Events() or to the completion of the command invoked in `RUN`. The way I'd expect the `done` to happen would be to fork off a go routine in the RUN state that is feeding `done := chan struct{}` when it's ready with `done <- struct{}{}`. Then you'd put the select below the go routine kickoff looking at both the channel and the sourceFileWatcher event feed (and maybe also the buildFileWatcher).

**Comment by mistic** [comment]
@achew22 thanks for looking into this. Overall I like the approach you suggested, the only thing I would want us to have in the future is a also a way to configure iBazel to just adopt the live reload behaviour for everything by default unless it founds a specific tag in a target to not do it `ibazel_skip_live_reload` while with the live reload behaviour disable the tag `ibazel_live_reload` should do the inverse.

**Comment by mistic** [comment]
This issue is being addressed at https://github.com/bazelbuild/bazel-watcher/pull/479

**Comment by mistic** [comment]
I would like to re-open this PR and be able to merge it with the upstream

**Comment by mistic** [comment]
This issue is not ready to be closed as the PRs to solve it were not merged
