### ISSUE TITLE
--define args not passed in `ibazel run`; but passed in `ibazel build`

### ISSUE THREAD

**Issue by zactivator** [bazelbuild/bazel-watcher#499]
**Describe the bug**
Passing a `--define` value, in this case required for a macro, does not work with `ibazel run` 
It does work, without any issue, in `ibazel build`

**Reproduction instructions**
[A link to a repo where this can be tested
](https://github.com/zactivator/ibazel-define-issue-repro)

See readme in repo for full example: `ibazel run --define=somevar=somevalue :rule` does not pass along `--define` parameter
```
ibazel run --define=replacement='s/hey/hi/g' //:sed_file
iBazel [5:55PM]: Querying for files to watch...
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
iBazel [5:55PM]: Running //:sed_file
Loading: 
Loading: 0 packages loaded
INFO: Build option --define has changed, discarding analysis cache.
Analyzing: target //:sed_file (0 packages loaded, 0 targets configured)
ERROR: .../ibazel-define-issue/BUILD.bazel:3:12: in cmd attribute of genrule rule //:sed_file: $(replacement) not defined. Since this rule was created by the macro 'custom_rule', the error might have been caused by the macro implementation
ERROR: .../bazel-define-issue/BUILD.bazel:3:12: Analysis of target '//:sed_file' failed
ERROR: Analysis of target '//:sed_file' failed; build aborted: 
INFO: Elapsed time: 0.120s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 7 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 7 targets configured)
```

**Expected behavior**
For the repo example, I expect it run a `sed` replacement on the file and then run the file. Instead I receive an error about `replacement` not having been defined. Running the rule with `bazel run` works exactly as expected.

**Version (please complete the following information):**
 - OS: macOS 12.0.1 (Intel)
 - ibazel Version: 0.14.0
 - Bazel version: 5.0.0
 
**Additional context**
This issue was previously reported in [issue242](https://github.com/bazelbuild/bazel-watcher/issues/242) and reportedly followed up on in [pr271](https://github.com/bazelbuild/bazel-watcher/pull/271). The test runs successfully (though fellow Mac users may have to [do some finagling](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93082))

**Comment by zactivator** [comment]
I updated macOS to 12.2. Same results.

**Comment by zactivator** [comment]
I figured out that `IBazel.queryArgs()` filters out the `--define` flag passed to `bazel.CQuery()`. Removing the check at  `ibazel/ibazel.go:544`, it complains about not recognizing `--define=replacement=...` but it will successfully run it. At least once. It seems that perhaps it also kills the watcher.

**Comment by zactivator** [comment]
Adding onto my exploration yesterday: `bazel.CQuery()` is totally cool with `IBazel.queryArgs()` returning the `--define` flag. 

`IBazel.watchFiles()` via `IBazel.queryForSourceFiles()`, however, relies on `bazel.Query()`, which does not like getting that `--define` flag, hence why the run was working but the watcher stopped. From [reading some](https://docs.bazel.build/versions/main/cquery.html) [bazel docs](https://docs.bazel.build/versions/main/configurable-attributes.html) it looks like `cquery` handles `select()` whereas `query` does not. This sounds like an explanation.

So, a solution which seems to be working great for me to get the value passed into the rules and keep the watcher running is to pass `bazel.CQuery()` an unfiltered `bazelArgs` list and pass `bazel.Query()` the one as currently filtered.

**Comment by mehtamanan** [comment]
@zactivator were you able to resolve this problem? i'm running into the same problem.
