### ISSUE TITLE
Document how this compares with the `--watchfs` bazel option

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#5]
I just noticed there's already an option to watch the input files.

eg. here's a commit where @damienmg improved how it's wired on Mac:
https://github.com/bazelbuild/bazel/commit/990fa00f7e1a7a8d5bcda78681a9cd7df5d5c023

But IIUC that option doesn't actually put Bazel in watch mode.
1) does ibazel benefit from using that flag as well?
2) should we add docs on that flag to clarify that it's not a watch mode and maybe point here?

**Comment by damienmg** [comment]
--watchfs use inotify and fsevents to be notified from file change to reduce the number of files bazel has to stat to observe changes.

bazel-watcher is a wrapper around bazel that use inotify / fsevents to trigger a bazel build/tests when an input has changed.

These are a bit different as the former is a performance optimization of Bazel and the latter more like an "ide"
