### ISSUE TITLE
Stop telling me iBazel can invoke programs like Gazelle buildozer, and other BUILD file generators automatically for you based on bazel output

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel-watcher#515]
Whenever I run ibazel, my console lights up with

```
################################################################################
# Did you know iBazel can invoke programs like Gazelle, buildozer, and         #
# other BUILD file generators for you automatically based on bazel output?     #
# Documentation at: https://github.com/bazelbuild/bazel-watcher#output-runner  #
################################################################################
```

I have quieted it by `echo [] > .bazel_fix_commands.json`, but it would be nicer if it weren't a problem in the first place.

**Comment by matthewjh** [comment]
I agree - this is annoying. How do we reopen this issue?

**Comment by jfirebaugh** [comment]
You can silence this by creating a `.bazel_fix_commands.json` file at the workspace root whose only contents are `[]`.

I agree there should be a more obvious way though, and this issue should be reopened.
