### ISSUE TITLE
data race in ibazel

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel-watcher#52]
Here's the stacktrace of a data race with the latest ibazel e8cbba37f5aa56f36e8561ec64128008c1f2cbe1. It came up in normal use.

It's the same one I mentioned in https://github.com/bazelbuild/bazel-watcher/pull/35

```
==================
WARNING: DATA RACE
Read at 0x00c42008c788 by goroutine 11:
  github.com/bazelbuild/bazel-watcher/ibazel/command.(*defaultCommand).IsSubprocessRunning()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/command/command.go:75 +0xae
  main.(*IBazel).handleSignals()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:96 +0x478
  main.New.func1()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:83 +0x38

Previous write at 0x00c42008c788 by main goroutine:
  os/exec.Command()
      /usr/local/Cellar/go/1.9.1/libexec/src/os/exec/exec.go:143 +0x157
  github.com/bazelbuild/bazel-watcher/ibazel/command.start()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/command/command.go:58 +0x397
  github.com/bazelbuild/bazel-watcher/ibazel/command.(*defaultCommand).Start()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/command/default_command.go:64 +0x161
  github.com/bazelbuild/bazel-watcher/ibazel/command.(*defaultCommand).NotifyOfChanges()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/command/default_command.go:75 +0x46
  main.(*IBazel).run()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:281 +0x155
  main.(*IBazel).(main.run)-fm()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:158 +0x5f
  main.(*IBazel).iteration()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:218 +0x656
  main.(*IBazel).loop()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:176 +0x126
  main.(*IBazel).Run()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:158 +0x169
  main.handle()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/main.go:130 +0x1cf
  main.main()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/main.go:116 +0x38a

Goroutine 11 (running) created at:
  main.New()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/ibazel.go:81 +0x1d0
  main.main()
      /Users/jmhodges/src/github.com/bazelbuild/bazel-watcher/ibazel/main.go:109 +0x202
==================
```

**Comment by achew22** [comment]
@jmhodges, thanks for filing the bug. Is there any circumstance where you're reliably able to trigger this? I'd like to add an end to end test to cover the mutex but will put it in either way.

**Comment by jmhodges** [comment]
No, there isn't. The e2e would just have to make lots of changes quickly and maybe hit it once in a while.

Are you running the tests with `--features=race` in CI? If they are comprehensive, you might trigger the race detector during normal runs.

**Comment by jmhodges** [comment]
It might be `--output_group=race`, depending on how you're building the Go code for the e2e tests. Needs a relatively recent version of rules_go.

**Comment by jmhodges** [comment]
Oh, I'm not getting it pretty reliably when sending a ctrl-c to ibazel.

**Comment by jmhodges** [comment]
Hey, this is still happening. Definitely occurs when you send SIGTERM to ibazel.

**Comment by dougkoch** [comment]
@jmhodges Do you build ibazel with `bazel build //ibazel/... --output_groups=race`? I'm trying to reproduce this, but haven't had any luck so far.

**Comment by jmhodges** [comment]
You need `--features=race` with the (newer) version of rules_go that this repo is using. The race is pretty obvious if look at how, for instance, `cmd.ProcessState` is accessed in `subprocessRunning` without locks through Terminate in the signal handling goroutine vs the main goroutine that also updates it without locks.

**Comment by dougkoch** [comment]
The race detector depends on cgo, so to use it in our CI we'd have to remove `pure = "on"` from `ibazel/BUILD`. However, it seems like it's already been decided that we're better off foregoing cgo dependencies for easier multi-OS compatibility. I'll probably have a PR ready in the near future that fixes this race.

**Comment by jmhodges** [comment]
It would just be for CI though? The race detector works well on all platforms.

I don't understand this objection.

**Comment by jmhodges** [comment]
Ping!

**Comment by achew22** [comment]
@jmhodges Yep. This is probably still an issue. That said, I use it most every day and I haven't run into it yet. Can you help me understand circumstances where this triggers so I can write a test-case that exercises it? We can just start slapping mutexes on things, but without a regression test it is liable to come back up again which is no good. How can we make sure this is fixed forever?

**Comment by jmhodges** [comment]
I don't think it's reasonable to ask an issue reporter to know your testing mechanisms when the race is obvious both on the screen and with the race detector build turned on.

Like, I've given you everything you need including the stacktraces to build one. Help me out here, as one of your users.

**Comment by jmhodges** [comment]
And to summarize: you you can get it by sending SIGTERM to ibazel (that `ctrl-c` comment I left) and getting a test build now requires `--features=race` in current versions rules_go for both `bazel test` and `bazel build`.

**Comment by achew22** [comment]
@jmhodges, I agree that it isn't fair. I'm doing this not because I'm paid by anyone but because I wanted to do it. I *do not* work on Bazel professionally. This project, unlike most of the other things under `bazelbuild`, is not staffed by full time people. I open sourced it because it felt like the right thing to do not because it is my job. This is a volunteer effort for me and when I take time out of my day to work on it, it comes at the expense of spending time with my friends and family.

**Comment by jmhodges** [comment]
Okay, I have posted a PR that turns on the race detector in CI and causes the tests to fail. It's at #121 

It seems there are other races, too.

**Comment by achew22** [comment]
To put a very fine point on this, I'm not doing it to spite you. I have to make a decision on what to work on with what little spare time I have and this is really hard for me to prioritize since I can't reproduce it on any of my computers even after trying REALLY hard. I wrote the e2e testing stuff so that I could run it overnight and have it run a crazy number of testcases. [This code](https://github.com/bazelbuild/bazel-watcher/blob/master/e2e/simple/simple_test.go#L92) used to be a for loop that ran till it timed out. I'm happy to help diagnose this and get a fix. I am REALLY happy to do that.

**Comment by jmhodges** [comment]
By the way, if you wanted to use the guts of github.com/jmhodges/justrun to do this stuff, that'd be cool and I'd be willing to help extract them. It solves much of the same problems as bazel-watcher and we fixed up the races (both data and logical) in its guts that bazel-watcher keeps running into.

**Comment by achew22** [comment]
I believe all the data races have been corrected for. If you encounter more, please reopen or file another issue.
