### ISSUE TITLE
Relation to Skaffold and similar tools

### ISSUE THREAD

**Issue by dudicoco** [bazelbuild/bazel-watcher#527]
There are several tools out there such as https://github.com/GoogleContainerTools/skaffold which can detect source code changes, rebuild and redeploy.

Does `bazel-watcher` make such tools redundant (assuming that you are working with bazel, of course)?

**Comment by achew22** [comment]
There may be places where `skaffold` is capable of doing more, but I don't know I've never used it. `bazel-watcher` is only focused on the bazel ecosystem and not with the things that surround it.

If your whole toolchain is encapsulated using bazel (be it skaffold, heroku, or anything else) `bazel-watcher` should be able to encompass it and those other tools would become part of a toolchain that `bazel-watcher drives`.

Feel free to reopen or leave another comment if you have more questions.
