### ISSUE TITLE
Migrate brew support from bazelbuild/homebrew-tap to Homebrew/homebrew-core

### ISSUE THREAD

**Issue by sventiffe** [bazelbuild/bazel-watcher#533]
We'd like to archive bazelbuild/homebrew-tap and the ibazel.rb formula is the only one left:
https://github.com/bazelbuild/homebrew-tap/blob/master/Formula/ibazel.rb

Would anyone consider migrating the formula to 
https://github.com/Homebrew/homebrew-core

**Comment by achew22** [comment]
TBH I had totally forgotten this exists.

Unfortunately, I don't know enough about the brew ecosystem to be able to contribute on this one. I was asked to do this by someone from the Bazel team a long, long time ago. I will take advice from the team on what to do if someone is just not supported any more. I would be happy to remove the instructions for installing with Brew and leaving just the `go install` and NPM based strategies if you think that's reasonable.

To be explicit, I don't think that keeping a tap around just for ibazel is a good idea and we should definitely get rid of that repo.

**Comment by sventiffe** [comment]
One way would be to move the formula as it is to homebrew-core but I suspect it has limited value as the current formula supports only one platform (and considering the performance of Apple Silicon machines, probably not even the most future proof one). It looks to me as if the "bottle" concept is the right approach for multi platform support but then I have only very limited knowledge of the homebrew ecosystem and the effort required to get familiar with it in order to produce a proper formula seems not to be justified for something that I consider probably rather low value/usage.

As long as nobody objects, I will archive that repo. The last formula will be still accessible for anyone who would like to sign up for proper homebrew support.
