### ISSUE TITLE
stream_test fails intermittently on Bazel CI (macOS)

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel-watcher#541]
Example failure: https://buildkite.com/bazel/bazel-watcher/builds/2461#01831a7b-49ab-460a-81a0-88445c552143 (this is with latest release Bazel, 5.3.0)

This test does not consistently fail (https://buildkite.com/bazel/bazel-watcher/builds?branch=master : it fails about 50% of the time.

**Comment by achew22** [comment]
I think this is a pretty simple timeout issue. Should be addressed by https://github.com/bazelbuild/bazel-watcher/pull/545

**Comment by achew22** [comment]
@meteorcloudy I think the issue is fixed. Generally speaking I'm happy to fix stuff like this but I have to say

> /cc @achew22 Can you look into those test failures? We'll have to disable Bazel watcher in downstream if the main build stays red.

felt pretty aggressive. This bug was filed 1 work day earlier. You might want to give people a bit more time before threatening them.

**Comment by meteorcloudy** [comment]
@achew22 Sorry about that, I might get confused with other not so responsive repositories, thanks for the fix!
