### ISSUE TITLE
Replace the "MAGIC" tag with something permanent; document it

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#55]
https://github.com/bazelbuild/bazel-watcher/blob/35e574c96178c8bc446c5052fde477f0a3866425/ibazel/ibazel.go#L265

@achew22 says the term `IBAZEL_MAGIC_TAG` was meant as a placeholder. I want to start depending on this feature so we should mature it to something we can live with, and document how it's used.

**Comment by achew22** [comment]
Not closing since it isn't documented.
