### ISSUE TITLE
Bazel watcher does not detect rules_rust changes

### ISSUE THREAD

**Issue by wmmiii** [bazelbuild/bazel-watcher#554]
**Describe the bug**
When running an executable from [rules_rust][1] such as `rust_binary` using the `ibazel run //:binary` command the watcher does not detect file system changes.

**Reproduction instructions**
See https://github.com/wmmiii/ibazel-rust-error for a minimal reproducible example including steps.

**Expected behavior**
It is expected that once one of the source files is changed that the `rust_binary` depends on that Bazel watcher will re-compile and re-execute the binary.

**`bazel query --output=build //path/to:target`**
If your issue is about a specific target in your system working, Please include the output of `bazel query --output=build //path/to:target`,

```
$ bazel query --output=build //:binary
# /path/to/root/BUILD:3:12
rust_binary(
  name = "binary",
  edition = "2018",
  srcs = ["//:main.rs"],
)
# Rule binary instantiated at (most recent call last):
#   /path/to/root/BUILD:3:12 in <toplevel>
# Rule rust_binary defined at (most recent call last):
#   /path/to/cache/bazel/_bazel_user/d5034bd6b99e22d57880e3656c6b7aba/external/rules_rust/rust/private/rust.bzl:829:19 in <toplevel>

Loading: 0 packages loaded
```
(user info redacted)

**Version (please complete the following information):**
 - OS: Ubuntu 20.05.5
 - Browser N/A
 - ibazel Version: `iBazel - Version Development` (built from 0c0b4953e71f2cae2ac3a6f2eb7dd1b05aec20b0)
 - Bazel version: bazel 5.3.1
 
**Additional context**

[1]: https://github.com/bazelbuild/rules_rust

**Comment by rejuvenile** [comment]
This is still an issue. github-actions is hiding real bugs and should be disabled.
