### ISSUE TITLE
log.Fatalf being called on finding WORKSPACE.bazel

### ISSUE THREAD

**Issue by jeremyeim** [bazelbuild/bazel-watcher#557]
**Describe the bug**
The latest release of bazel-watcher doesn't work with a workspace with a `WORKSPACE.bazel` 

**Reproduction instructions**
https://github.com/bazelbuild/bazel-watcher/blob/0c0b4953e71f2cae2ac3a6f2eb7dd1b05aec20b0/internal/ibazel/workspace/workspace.go#L59 shouldn't be calling `log.Fatalf`

**Expected behavior**
https://github.com/bazelbuild/bazel-watcher/blob/0c0b4953e71f2cae2ac3a6f2eb7dd1b05aec20b0/internal/ibazel/workspace/workspace.go#L59 shouldn't be calling `log.Fatalf`

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser N/A
 - ibazel Version: iBazel - Version v0.18.0
 - Bazel version: 5.3.0

**Comment by achew22** [comment]
This seems like a reasonably straightforward fix. Thanks for doing the research to find the problematic line! How can I help you contribute a patch to solve the problem?
