### ISSUE TITLE
fsevents silently fails to watch when there are more than 4096 directories

### ISSUE THREAD

**Issue by WearyMonkey** [bazelbuild/bazel-watcher#558]
**Describe the bug**

For large targets that involve more than 4096 directories, changes do not trigger rebuilds.

The fsevents package specifies a maximum of 4096 directories watched and recommended using recursive watches:

https://github.com/fsnotify/fsevents/blob/main/README.md#caveats

**Version (please complete the following information):**
 - OS: osx 12.6 M1
 - ibazel Version 0.16.2
 - Bazel version 5.1.1

**Comment by WearyMonkey** [comment]
Raised a potential fix here:
https://github.com/bazelbuild/bazel-watcher/pull/559

**Comment by achew22** [comment]
I believe this was fixed by the pr. If it recurs please feel free to reopen this
