### ISSUE TITLE
Flag --incompatible_config_setting_private_default_visibility will break Bazel watcher in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel-watcher#565]
Incompatible flag `--incompatible_config_setting_private_default_visibility` will be enabled by default in the next major release (Bazel 7.0), thus breaking Bazel watcher. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: https://github.com/bazelbuild/bazel/issues/12933.

Please check the following CI builds for build and test results:

- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-4a0b-4a1a-b57d-7bcdd8d11ae8)
- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-4a0e-4f7c-8044-0797abed1635)
- [Ubuntu 16.04, OpenJDK 8](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-4a08-40b0-97e6-1a9e95b7e3c2)
- [Ubuntu 18.04, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-4a05-4a15-bd4b-87d9df6844b6)
- [Windows, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1341#0184a208-4a10-4ddf-95b3-a2976db607b3)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by achew22** [comment]
I think this will be fixed by https://github.com/bazelbuild/bazel-watcher/pull/563. On the next run I expect this will be resolved.
