### ISSUE TITLE
Bazel watcher broken with Bazel@HEAD in Bazel downstream pipeline

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel-watcher#567]
Context: https://github.com/bazelbuild/bazel/issues/16746

Some tests in Bazel watcher seem to parse the output log of Bazel and https://github.com/bazelbuild/bazel/commit/6e945e8ab422ca0a195d09899cce61ba6c0cfa59 broke the tests, please help resolve this issue so that we can make sure Bazel watcher is green in [Bazel downstream pipeline](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2760) and keep detecting breaking changes/Bazel bugs that break Bazel watcher ;)

**Comment by achew22** [comment]
@meteorcloudy do you have any ideas on how I could differentiate between the two compiled versions of bazel in the ci system? How can I deterministically determine if this cl is a part of the bazel I have invoked?

**Comment by meteorcloudy** [comment]
I guess you have to figure out which commit your Bazel is built at, then check if the CL (commit) is a parent of that commit?

But for this specific failure, I'm fairly certain it's caused by https://github.com/bazelbuild/bazel/commit/6e945e8ab422ca0a195d09899cce61ba6c0cfa59

**Comment by achew22** [comment]
So in order to implement this test properly I need to clone the bazel repo at the commit that it was compiled from and then do an inclusion check on that particular commit from the bazel tree?

**Comment by meteorcloudy** [comment]
@achew22 Oh I see, I thought you were just debugging. If you want to implement this check in the Bazel watcher, I think it's fine to assume any Bazel version >= 6.0 should contain this change, if the Bazel binary has no version, just assume it's HEAD (thus > 6.0)

**Comment by meteorcloudy** [comment]
Bazel watcher still failing with Bazel@HEAD: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2908#0186de4b-ae80-40c2-bea2-a1cd2a0a1626

Can we disable the failing test to get a green CI?
