### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break Bazel watcher in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazel-watcher#572]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking Bazel watcher. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-09d0-4c6f-8d34-20404770ea4f)
- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-09d3-417d-b872-ea9b982a16a8)
- [Ubuntu 16.04 OpenJDK 8](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-09cd-47ea-a82b-049af6fcd866)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-09ca-4563-8bd5-889043bff149)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-09d6-4893-8aa9-25630f4c2951)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by keertk** [comment]
Not stale - errors still need to be fixed

**Comment by achew22** [comment]
@keertk maybe I'm misreading, but when I click the links that are above they look like the `bazel-watcher` tasks are passing. Could you clarify a bit more?

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/37206/219534677-36091441-b67f-4ff7-b802-3fbed082cd6c.png">


When I click on the provided link for [OpenJDK 11, Xcode](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-09d0-4c6f-8d34-20404770ea4f), I see a page with a green check as well?

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/37206/219534752-33fed348-d54a-489a-9d31-f6de57f01c31.png">

**Comment by keertk** [comment]
Hi @achew22 you can look under `Running Bazel with --incompatible_disable_starlark_host_transitions`

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/110264242/219538471-30f109ed-b39c-4437-b668-bee800981658.png">

This is one of the errors:
```
bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --jobs=36 --announce_rc --experimental_repository_cache_hardlinks --disk_cache= --sandbox_writable_path=/var/tmp/_bazel_buildkite/cache/repos/v1 --test_env=REPOSITORY_CACHE=/var/tmp/_bazel_buildkite/cache/repos/v1 --remote_cache=http://100.107.73.148 --remote_timeout=60 --remote_max_connections=200 --remote_default_platform_properties=properties:{name:"cache-silo-key" value:"49e868fd19c783d6f53c975f6ca88acfc8b5830b0793f4698cbc32cefcda8c8b"} --build_tag_filters=-nomacos --test_env=HOME --test_env=BAZELISK_USER_AGENT --test_env=USE_BAZEL_VERSION --incompatible_disable_starlark_host_transitions -- ...
--
  | (11:23:10) WARNING: Option 'remote_default_platform_properties' is deprecated: --remote_default_platform_properties has been deprecated in favor of --remote_default_exec_properties.
  | (11:23:10) INFO: Invocation ID: 36a72a2f-5429-466f-a795-8a0d7e495e6e
  | (11:23:10) INFO: Options provided by the client:
  | Inherited 'common' options: --isatty=1 --terminal_columns=0
  | (11:23:10) INFO: Reading rc options for 'build' from /Users/buildkite/builds/bk-imacpro-15/bazel-downstream-projects/bazel-watcher/.bazelrc:
  | 'build' options: --workspace_status_command=python3 tools/workplace_status.py
  | (11:23:11) WARNING: Option 'remote_default_platform_properties' is deprecated: --remote_default_platform_properties has been deprecated in favor of --remote_default_exec_properties.
  | (11:23:11) INFO: Current date is 2022-12-15
  | (11:23:11) ERROR: Traceback (most recent call last):
  | File "/private/var/tmp/_bazel_buildkite/62aafb6863f3e91c21fe2c420944323e/external/io_bazel_rules_go/extras/embed_data.bzl", line 133, column 29, in <toplevel>
  | "_embed": attr.label(
  | Error in label: 'cfg = "host"' is deprecated and should no longer be used. Please use 'cfg = "exec"' instead.
  | (11:23:11) ERROR: Skipping '...': error loading package under directory '': error loading package 'internal/ibazel/output_runner': at /private/var/tmp/_bazel_buildkite/62aafb6863f3e91c21fe2c420944323e/external/io_bazel_rules_go/go/def.bzl:58:5: initialization of module 'extras/embed_data.bzl' failed
  | (11:23:11) WARNING: Target pattern parsing failed.
  | (11:23:11) ERROR: error loading package under directory '': error loading package 'internal/ibazel/output_runner': at /private/var/tmp/_bazel_buildkite/62aafb6863f3e91c21fe2c420944323e/external/io_bazel_rules_go/go/def.bzl:58:5: initialization of module 'extras/embed_data.bzl' failed
  | (11:23:11) INFO: Elapsed time: 0.953s
  | (11:23:11) INFO: 0 processes.
  | (11:23:11) FAILED: Build did NOT complete successfully (0 packages loaded)
```

Sorry that this was confusing! I hope this helps.

**Comment by achew22** [comment]
I've run this down now and I'm blocked on https://github.com/bazelbuild/rules_go/issues/3403. I've removed my dependency  on the old go embed data stuff in https://github.com/bazelbuild/bazel-watcher/pull/589 but this will be blocked until rules_go actually removes that.

That said, the `go_embed_data` feature has been deprecated for a while and deletion might be an easy fix if people are amenable.

**Comment by sgowroji** [comment]
Hi @achew22, Could you please share any significant update on this issue ?
