### ISSUE TITLE
feature request: configurable path for `bazel_fix_commands.json`

### ISSUE THREAD

**Issue by aw185176** [bazelbuild/bazel-watcher#576]

**Comment by achew22** [comment]
Hey @aw185176,

I would love to see a contribution on that front. As a straw man, I'd personally like to have a `~/.bazel_watcher.json` file that would be able to configure some defaults in all my repos.

https://github.com/bazelbuild/bazel-watcher/blob/33c569443dadc5ab842b94ccf609b867b0b4900f/internal/ibazel/output_runner/output_runner.go#L103-L136

is the place where this is defined right now. It would be reasonably straightforward to refactor that to read from a set of locations, preferring the first one it matches. What would you think about taking that on as a first step?
