### ISSUE TITLE
TestOutputRunnerUniqueCommandsOnly broken with Bazel@HEAD

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel-watcher#590]
**Describe the bug**
The //internal/e2e/output_runner:output_runner_test, `TestOutputRunnerUniqueCommandsOnly` test is broken with Bazel@HEAD
Full log: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2872#0186722a-3d2b-4ae6-ae33-8e036c7bbdd2

Breaking change is Bazel that most likely caused it is:
https://github.com/bazelbuild/bazel/commit/6e945e8ab422ca0a195d09899cce61ba6c0cfa59

**Version (please complete the following information):**
 - OS: all
 - ibazel Version: head 
 - Bazel version: head

**Comment by comius** [comment]
Assert that fails is: https://github.com/bazelbuild/bazel-watcher/blob/master/internal/e2e/output_runner/output_runner_test.go#L160

**Comment by justinhorvitz** [comment]
See https://github.com/bazelbuild/bazel/commit/6e945e8ab422ca0a195d09899cce61ba6c0cfa59#commitcomment-99640134.
