### ISSUE TITLE
ibazel ought to use CQuery instead of regular query

### ISSUE THREAD

**Issue by jakeleventhal** [bazelbuild/bazel-watcher#594]
**Describe the bug**
Running `bazel build <target>` then `bazel query <target>` invalidates the cache sometimes because `bazel query` doesn't consider select statements.

**Reproduction instructions**
Any repo with a target with select statements. Run the above commands and see the cache is invalidated.

**Expected behavior**
The cache should not be invalidated. This leads to really long boot up times.

**Version (please complete the following information):**
 - OS: `MacOS 13.3`
 - Browser: N/A
 - ibazel Version: `v0.16.2`
 - Bazel version: `6.1.0`

**Comment by loeffel-io** [comment]
same here!

**Comment by purkhusid** [comment]
Same error here. Any chance we could rollback the change @achew22 ?

**Comment by achew22** [comment]
Yeah, let's roll it back

**Comment by achew22** [comment]
Looks like there may be more complexity here than initially thought. Rolling back to restore functionality. Thanks for the reporting everyone!

**Comment by jakeleventhal** [comment]
This issue should be reopened. The cache invalidation issue still exists
