### ISSUE TITLE
npm package is not updated to the latest version

### ISSUE THREAD

**Issue by condemil** [bazelbuild/bazel-watcher#600]
**Describe the bug**
According to https://www.npmjs.com/package/@bazel/ibazel the latest published version is 0.16.2, but it should be [0.22.0](https://github.com/bazelbuild/bazel-watcher/releases)

**Comment by jfirebaugh** [comment]
This is still relevant. Please reopen.

**Comment by alexeagle** [comment]
It seems there's meant to be automation for this
https://github.com/bazelbuild/bazel-watcher/blob/f78923be89d6e9c6627c8a190a1ed3c52873ce11/.github/workflows/release.yaml#L120-L143

but the release_npm step is red for the last release: https://github.com/bazelbuild/bazel-watcher/actions/runs/5330775118

@achew22 would you like some help on that?
