### ISSUE TITLE
Embedding is now better handled by using rules_go's built-in embedding functionality

### ISSUE THREAD

**Issue by JedWalton** [bazelbuild/bazel-watcher#601]
Embedding is now better handled by using rules_go's built-in embedding functionality (https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/rules.md#go_library-embedsrcs). The `go_embed_data` rule is deprecated and will be removed in rules_go version 0.39.

When running: `$ bazel build //cmd/ibazel`

We get this output
` DEBUG: /home/jed/.cache/bazel/_bazel_jed/af5ae91ebf75b60dda82342a83fceee7/external/io_bazel_rules_go/extras/embed_data.bzl:43:10: Embedding is now better handled by using rules_go's built-in embedding functionality (https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/rules.md#go_library-embedsrcs). The `go_embed_data` rule is deprecated and will be removed in rules_go version 0.39.`

**Comment by achew22** [comment]
This would be a great first contribution! How can I help you get in a PR to make the change?
