### ISSUE TITLE
BUILD file changes not detected anymore

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/bazel-watcher#603]
**Describe the bug**
BUILD file changes are not detected by bazel-watcher and when bazel-watcher is started it non-fatally emits the following error:
```
ERROR: Error doing post analysis query: Evaluation failed: buildfiles() doesn't make sense for the configured target graph
```

The issue is very likely related to this change: https://github.com/bazelbuild/bazel-watcher/commit/ac2ce9f7406798b10c584efbac14ca05ba8cd818

The change moves the queries bazel-watcher does over to cquery but cquery does not support `buildfiles` in it's queries.

**Expected behavior**
BUILD file changes should be detected

**Version (please complete the following information):**
 - OS: Fedora 37
 - ibazel Version v0.22.0
 - Bazel version 6.1.1

**Comment by achew22** [comment]
Can you confirm this is fixed in https://github.com/bazelbuild/bazel-watcher/releases/tag/v0.23.0?

**Comment by purkhusid** [comment]
The Linux binaries are missing from the release. Will test it as soon as they get published.

**Comment by achew22** [comment]
Sorry about that, they're sitting in the GitHub actions queue here https://github.com/bazelbuild/bazel-watcher/actions/runs/4736205730

**Comment by jakeleventhal** [comment]
This issue can close
