### ISSUE TITLE
bazel-watcher requires an ancient version of bazel

### ISSUE THREAD

**Issue by simmonmt** [bazelbuild/bazel-watcher#610]
**Describe the bug**

`.bazelversion` specifies an ancient version of bazel -- 5.4.0. Is this necessary? It seems to build just fine with 6.1.2.

I ask because the presence of this file seems to make it exceedingly unlikely that the [Compiling yourself](https://github.com/bazelbuild/bazel-watcher#compiling-yourself) instructions will work unless the user happens to have that specific version in their path.

**Comment by achew22** [comment]
Great to hear the upgrade path is smooth! I would be more than happy to merge a pr if you want to send one over
