### ISSUE TITLE
Linux actifacts are not being published for releases

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/bazel-watcher#614]
For the last 2 releases there are only darwin artifacts. The action that publishes the linux artifacts is failing for some reason: https://github.com/bazelbuild/bazel-watcher/actions/runs/4873955009/jobs/8694254065

**Comment by purkhusid** [comment]
This is also the case for Windows

**Comment by achew22** [comment]
Should be fixed in https://github.com/bazelbuild/bazel-watcher/releases/tag/v0.23.2. Turns out Ubuntu 18.04 was deprecated. Sorry about that!
