### ISSUE TITLE
Update to use bazel 6.x

### ISSUE THREAD

**Issue by chenrui333** [bazelbuild/bazel-watcher#616]
Can we get [this PR](https://github.com/bazelbuild/bazel-watcher/pull/575) merged? cc @achew22 

relates to https://github.com/Homebrew/homebrew-core/pull/134405

**Comment by achew22** [comment]
As I [commented on the PR](https://github.com/bazelbuild/bazel-watcher/pull/575#issuecomment-1605266454) I'm more than happy to merge it once the tests pass. If you'd like to send in a PR I would be very receptive to review

**Comment by chenrui333** [comment]
Aha, let me also take a stab on it. :)

**Comment by phaedon** [comment]
Will this enable running with --enable_bzlmod (i.e. reading MODULE.bazel with external dependencies from the Central Repository)?

**Comment by achew22** [comment]
No, that is a setting in bazel itself. If you would like to add a flag that's passed down you can send a pr to add it to this list https://github.com/bazelbuild/bazel-watcher/blob/master/cmd/ibazel/main.go#L37
