### ISSUE TITLE
Question: How to disable banner?

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel-watcher#643]
How do I disable this banner?

```
iBazel [12:54PM]: Build error: exit status 3

################################################################################
# Did you know iBazel can invoke programs like Gazelle, buildozer, and         #
# other BUILD file generators for you automatically based on bazel output?     #
# Documentation at: https://github.com/bazelbuild/bazel-watcher#output-runner  #
################################################################################

```

**Comment by prestonvanloon** [comment]
Can the banner just be removed? It's a ton of real estate in the console.

**Comment by achew22** [comment]
Sure can:

```sh
echo "[]" > .bazel_fix_commands.json
```

This is documented in the [README.md](https://github.com/bazelbuild/bazel-watcher?tab=readme-ov-file#disabling-output-runner). Hope that helps!

**Comment by prestonvanloon** [comment]
@achew22 that isn't ideal to have to add a new file in every bazel project. Would you consider removing the banner?

https://github.com/prestonvanloon/bazel-watcher/commit/ae98dcb740674f53e0a1d07f63ef9c012c7d54f0

I'll be maintaining this change and building from source because I find this banner to be very invasive in my workflow. Happy to send this as a PR, if it will be considered.

**Comment by achew22** [comment]
I would be receptive to a patch that creates a `~/.ibazel` (or whatever the
modern version of that is) that allows disabling it globally
