### ISSUE TITLE
ibazel does not support a workspace whose path may contain symlinks

### ISSUE THREAD

**Issue by klandergren** [bazelbuild/bazel-watcher#649]
**Describe the bug**
I noticed that `ibazel` seemed to either not rebuild or inconsistently rebuild some of my projects. Digging into it turned up that ibazel does not resolve symlinks before passing the directory paths to `fsevents`. 

This results in a scenario where either:

1. `fsevents` is watching a symlink, which it states in its README: ["FSEvents returns events for the named path only, so unless you want to follow updates to a symlink itself (unlikely), you should use filepath.EvalSymlinks to get the target path to watch."](https://github.com/fsnotify/fsevents/blob/69514f1df48b90c0675b339e892e8230e057548a/README.md?plain=1#L13)
2. the events reported by `fsevents` contain paths that do not match [the non-resolved paths ibazel is monitoring](https://github.com/bazelbuild/bazel-watcher/blob/be201b413f68f721408a4a615d57a568aa82642f/internal/ibazel/ibazel.go#L532)

**Reproduction instructions**

1. `git clone https://github.com/klandergren/ibazel-symlinked-workspace`
1. `cd holder/my-project`
1. `ibazel run //:simple`
1. Edit `working-directory/simple.sh` to have a different message
1. See `ibazel` not rebuilding

**Expected behavior**
`ibazel` detects the source file change in `simple.sh` and triggers a rebuild / re-run.

**Actual behavior**
`ibazel` does not detect the source file change and does not rebuild / re-run.

**Version (please complete the following information):**
 - OS: 13.6.5 (22G621)
 - ibazel Version: `iBazel - Version 0.24.0`
 - Bazel version:
 ```
Bazelisk version: development
Build label: 7.1.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Mar 11 18:00:10 2024 (1710180010)
Build timestamp: 1710180010
Build timestamp as int: 1710180010
 ```
 
**Additional context**
This does not touch on the [issue of whether or not bazel should be resolving symlinks within a workspace](https://github.com/bazelbuild/bazel/issues/7057), just on situations where the workspace may be visited through a symlink.

**Comment by achew22** [comment]
This is fixed thanks to your pr and should be released in the next few minutes in all the normal places.

Thanks!
