### ISSUE TITLE
non-conventional version tag for 0.25.1

### ISSUE THREAD

**Issue by timsutton** [bazelbuild/bazel-watcher#652]
**Describe the bug**
👋 while looking to bump this tool in homebrew/core, I noticed the version tag uses an upper-case `V` instead of the usual lower-case `v`. Just flagging this if it's possible to make a fixed tag or to note it for a future release.

**Comment by achew22** [comment]
Happy to https://github.com/bazelbuild/bazel-watcher/releases/tag/v0.25.1
