### ISSUE TITLE
e2e non-determinism after addition of lifecycle hooks

### ISSUE THREAD

**Issue by dougkoch** [bazelbuild/bazel-watcher#95]
I've run the e2e tests repeatedly with `--cache_test_results=no` on every recent commit, and I've concluded that both the `live_reload` and `simple` tests started failing non-deterministically on the commit that added lifecycle hooks (b87e958).

**Comment by achew22** [comment]
For the record, the best way I've found to find these sorts of things is:

```
git bisect start HEAD v0.1.1 --      # HEAD is bad, v0.1.1 is good
git bisect run bazel test --cache_test_results=no --runs_per_test=50 //...
```

It's a really nice way to find the issue.
