### ISSUE TITLE
Watches 0 files when target is in a different workspace

### ISSUE THREAD

**Issue by alxhub** [bazelbuild/bazel-watcher#97]
```
$ ibazel test @angular//src/sw-config:test
State: QUERY
Querying for BUILD files...
WARNING: Switched off --watchfs again... temporarily falling back to manually checking files for changes
Watching: 0 files
Querying for source files...
Watching: 0 files
State: RUN
Testing @angular//src/sw-config:test
INFO: Analysed target @angular//src/sw-config:test (0 packages loaded).
INFO: Found 1 test target...
Target @angular//src/sw-config:test up-to-date:
  /private/var/tmp/_bazel_arick/c12f4ea4eaf7a974edf6cb95dd136227/execroot/angular_src/bazel-out/darwin-fastbuild/bin/external/angular/src/sw-config/darwin_amd64_stripped/test
INFO: Elapsed time: 0.270s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
@angular//src/sw-config:test                                    (cached) PASSED in 0.1s

Executed 0 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
State: WAIT

$ bazel query 'deps(@angular//src/sw-config:test)' | sort | grep _test
go_test rule @angular//src/sw-config:test
source file @angular//src/sw-config:glob_test.go
source file @angular//src/sw-config:manifest_test.go
source file @com_github_google_protobuf//:src/google/protobuf/arena_test_util.h
source file @com_github_google_protobuf//:src/google/protobuf/map_lite_test_util.h
source file @com_github_google_protobuf//:src/google/protobuf/map_test_util.h
source file @com_github_google_protobuf//:src/google/protobuf/map_test_util_impl.h
source file @com_github_google_protobuf//:src/google/protobuf/util/internal/type_info_test_helper.cc
source file @com_github_google_protobuf//:src/google/protobuf/util/internal/type_info_test_helper.h
```

Changing manifest_test.go failed to rerun the tests.

**Comment by achew22** [comment]
@alxhub, I hadn't considered this use case yet. Could you help me understand your flow? What is the circumstance where you would like to run the `@angular//...` tests and watch the files? How are you tracking those dependencies? Does `@angular//` depend on any targets that exist in your main repo (aka `@`)? Is this a one off test where you want to verify your upstream dependencies are functioning? Thanks so much!

**Comment by alexeagle** [comment]
Ran into this again today with @Toxicable 
in rules_nodejs we have a dubious setup where some tests are in a nested workspace (because we want to check that the skylark logic handles cross-workspace dependencies)

in the root directory, if you
`ibazel test @program_example//:test`
ibazel will run this query
```
$ bazel query "kind('source file', deps(set(@program_example//:test)))"
@program_example//:index.spec.js
```
it does not find the `index.spec.js` file, and watches no files.

If you first `cd examples/program` and then `ibazel test :test` then the query doesn't return any fully-qualified workspaces in the labels, and it works.

**Comment by alexeagle** [comment]
At a minimum, it would be really helpful if ibazel warned loudly when watching no files

**Comment by achew22** [comment]
@alexeagle I've been looking at the blaze query stuff and I can't figure out a way to go from arbitrary path to file path that traverses workspaces. Do you have any ideas on how to do that? Without that I think the best that can be done is a big scary warning when there are no matches. WDYT?

**Comment by alexeagle** [comment]
Let's ask the Bazel team about it. I think this is an unusual use case so a
scary warning is probably fine.
